#!/usr/bin/env python3
# Copyright (c) Advanced Micro Devices, Inc., or its affiliates.
# SPDX-License-Identifier: MIT
#
# STRESS variant of gfx942_attention_tiled_2d_emit.py -- wide adversarial config
# set for deep Python-vs-C parity. Prints lower_kernel_to_llvm(...) to stdout.
from rocke.instances.gfx942.attention_tiled_2d import (
    UnifiedAttention2DTiledSpec,
    build_unified_attention_2d_tiled,
)
from _emit_common import run_emit


_CONFIGS = {
    # --- baseline / dtype / mask-feature variety ---
    0: dict(
        head_size=64,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
    ),
    1: dict(
        head_size=64,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="fp16",
        use_sinks=True,
        sliding_window=2048,
        has_softcap=True,
    ),
    2: dict(
        head_size=64,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=True,
        sliding_window=1,
        has_softcap=False,
    ),
    3: dict(
        head_size=64,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=131072,
        has_softcap=False,
    ),
    4: dict(
        head_size=64,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="fp16",
        use_sinks=True,
        sliding_window=512,
        has_softcap=True,
        use_alibi=True,
        use_qq_bias=True,
    ),
    # --- head_size edge / prime-ish ---
    5: dict(
        head_size=32,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
    ),
    6: dict(
        head_size=96,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
    ),
    7: dict(
        head_size=128,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="fp16",
        use_sinks=True,
        sliding_window=0,
        has_softcap=True,
    ),
    8: dict(
        head_size=192,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
    ),
    9: dict(
        head_size=256,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
    ),
    10: dict(
        head_size=512,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
    ),
    # --- block_size edge / non-power-of-two ---
    11: dict(
        head_size=64,
        block_size=16,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
    ),
    12: dict(
        head_size=64,
        block_size=64,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
    ),
    13: dict(
        head_size=64,
        block_size=96,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
    ),
    14: dict(
        head_size=64,
        block_size=160,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
    ),
    15: dict(
        head_size=64,
        block_size=256,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
    ),
    # --- head-count / GQA / primes / indivisible ratios ---
    16: dict(
        head_size=64,
        block_size=32,
        num_query_heads=1,
        num_kv_heads=1,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
    ),
    17: dict(
        head_size=64,
        block_size=32,
        num_query_heads=7,
        num_kv_heads=7,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
    ),
    18: dict(
        head_size=64,
        block_size=32,
        num_query_heads=13,
        num_kv_heads=13,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
    ),
    19: dict(
        head_size=64,
        block_size=32,
        num_query_heads=64,
        num_kv_heads=8,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
    ),
    20: dict(
        head_size=64,
        block_size=32,
        num_query_heads=40,
        num_kv_heads=8,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
    ),
    21: dict(
        head_size=64,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=5,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
    ),
    22: dict(
        head_size=64,
        block_size=32,
        num_query_heads=128,
        num_kv_heads=1,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
    ),
    # --- num_warps / block_m variety ---
    23: dict(
        head_size=64,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        num_warps=2,
    ),
    24: dict(
        head_size=64,
        block_size=32,
        num_query_heads=64,
        num_kv_heads=8,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        num_warps=4,
    ),
    # --- tile_size knob ---
    25: dict(
        head_size=64,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        tile_size=64,
    ),
    26: dict(
        head_size=64,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        tile_size=128,
    ),
    27: dict(
        head_size=128,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="fp16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        num_warps=2,
        tile_size=128,
    ),
    # --- kv_cache_policy variety ---
    28: dict(
        head_size=64,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        kv_cache_policy="all",
    ),
    29: dict(
        head_size=64,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        kv_cache_policy="global",
    ),
    30: dict(
        head_size=64,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        kv_cache_policy="nt",
    ),
    # --- waves_per_eu / num_seqs (binary-search iters) ---
    31: dict(
        head_size=64,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        waves_per_eu=2,
    ),
    32: dict(
        head_size=64,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        num_seqs=1,
    ),
    33: dict(
        head_size=64,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        num_seqs=257,
    ),
    34: dict(
        head_size=64,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        num_seqs=1000000,
    ),
    # --- 32x32x8 wide-fragment / transposed-x8 fp16 paths ---
    35: dict(
        head_size=128,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="fp16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        use_mfma_32x32x8=True,
        block_m_per_warp=32,
        tile_size=64,
    ),
    36: dict(
        head_size=64,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="fp16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        use_mfma_32x32x8=True,
        use_transposed_qk_32x32=True,
        block_m_per_warp=32,
        tile_size=64,
    ),
    # --- register_pv bf16 path + big composite ---
    37: dict(
        head_size=64,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        use_register_pv=True,
    ),
    38: dict(
        head_size=128,
        block_size=128,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=True,
        sliding_window=4096,
        has_softcap=True,
        num_warps=8,
        tile_size=128,
    ),
    39: dict(
        head_size=384,
        block_size=128,
        num_query_heads=16,
        num_kv_heads=4,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
    ),
    # --- idx40-49: gfx942 wide-K (32x32x8) transposed-x8 coverage the gate
    #     never sampled. The production flash selector (_enable_gfx942_*_flash)
    #     routes the bf16/fp16 wide path here; this exercises the bf16 32x32x8
    #     MFMA atom (`.1k` intrinsic) across d64/d128/d256/GQA/sinks+SW plus
    #     kv_cache_policy and i64-KV on the wide path. (The deeper flash
    #     sub-knobs -- cfvst V-store scheduling, K single-buffer drain, the
    #     sliced-K ring, direct-Q-global, and the mask-limit/invariant-hoist
    #     VALU stack -- are surfaced as known unported gfx942 C-twin paths; see
    #     the task report. They are NOT sampled here because the C twin cannot
    #     yet match them byte-for-byte.) ---
    # idx40: bf16 transposed-x8 d64 (exercises the bf16 32x32x8 atom).
    40: dict(
        head_size=64,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        num_warps=4,
        block_m_per_warp=32,
        tile_size=64,
        use_mfma_32x32x8=True,
        use_transposed_qk_32x32=True,
    ),
    # idx41: bf16 transposed-x8 d128 nw2.
    41: dict(
        head_size=128,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        num_warps=2,
        block_m_per_warp=32,
        tile_size=64,
        use_mfma_32x32x8=True,
        use_transposed_qk_32x32=True,
    ),
    # idx42: bf16 transposed-x8 GQA-8 (the production prefill head ratio).
    42: dict(
        head_size=64,
        block_size=32,
        num_query_heads=64,
        num_kv_heads=8,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        num_warps=4,
        block_m_per_warp=32,
        tile_size=64,
        use_mfma_32x32x8=True,
        use_transposed_qk_32x32=True,
    ),
    # idx43: bf16 transposed-x8 with sinks + sliding window (mask features on
    #        the wide atom).
    43: dict(
        head_size=64,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=True,
        sliding_window=2048,
        has_softcap=False,
        num_warps=4,
        block_m_per_warp=32,
        tile_size=64,
        use_mfma_32x32x8=True,
        use_transposed_qk_32x32=True,
    ),
    # idx44: fp16 transposed-x8 d128 nw2 (the D128 wide-atom geometry).
    44: dict(
        head_size=128,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="fp16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        num_warps=2,
        block_m_per_warp=32,
        tile_size=64,
        use_mfma_32x32x8=True,
        use_transposed_qk_32x32=True,
    ),
    # idx45: bf16 transposed-x8 + kv_cache_policy="nt" on the wide path.
    45: dict(
        head_size=64,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        num_warps=4,
        block_m_per_warp=32,
        tile_size=64,
        use_mfma_32x32x8=True,
        use_transposed_qk_32x32=True,
        kv_cache_policy="nt",
    ),
    # idx46: bf16 transposed-x8 with block_size=16 (paged-KV block edge on the
    #        wide atom).
    46: dict(
        head_size=64,
        block_size=16,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        num_warps=4,
        block_m_per_warp=32,
        tile_size=64,
        use_mfma_32x32x8=True,
        use_transposed_qk_32x32=True,
    ),
    # idx47: bf16 transposed-x8 + softcap on the wide atom.
    47: dict(
        head_size=64,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=True,
        num_warps=4,
        block_m_per_warp=32,
        tile_size=64,
        use_mfma_32x32x8=True,
        use_transposed_qk_32x32=True,
    ),
    # idx48: bf16 transposed-x8 + kv_cache_policy="global".
    48: dict(
        head_size=64,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        num_warps=4,
        block_m_per_warp=32,
        tile_size=64,
        use_mfma_32x32x8=True,
        use_transposed_qk_32x32=True,
        kv_cache_policy="global",
    ),
    # idx49: bf16 transposed-x8 d128 GQA (h32 kv8) on the wide atom.
    49: dict(
        head_size=128,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=8,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        num_warps=2,
        block_m_per_warp=32,
        tile_size=64,
        use_mfma_32x32x8=True,
        use_transposed_qk_32x32=True,
    ),
}


def _kernel(idx: int):
    if idx not in _CONFIGS:
        raise SystemExit(f"unknown config index {idx}")
    spec = UnifiedAttention2DTiledSpec(**_CONFIGS[idx])
    return build_unified_attention_2d_tiled(spec, arch="gfx942")


def _emit_build(kernel, arch=None):
    return kernel


def main() -> int:
    return run_emit(
        _kernel,
        _emit_build,
        usage="usage: stress_emit.py <config_index>\n",
        arch="gfx942",
    )


if __name__ == "__main__":
    raise SystemExit(main())
