#!/usr/bin/env python3
# Copyright (c) Advanced Micro Devices, Inc., or its affiliates.
# SPDX-License-Identifier: MIT
#
# tests/parity/gfx950_attention_tiled_2d_emit.py -- Python reference emitter for
# the gfx950 WIDE-ATOM tiled-2D unified-attention kernel parity harness.
#
# Selects one of the sampled configs by argv[1], builds a
# UnifiedAttention2DTiledSpec, emits the kernel via
# build_unified_attention_2d_tiled(spec, arch="gfx950") and prints
# lower_kernel_to_llvm(kernel, arch="gfx950") to stdout so it can be
# byte-compared with the C emitter gfx950_attention_tiled_2d_emit.c.
#
# The config table is kept IN LOCKSTEP with the C make_spec() switch (same index
# -> same UnifiedAttention2DTiledSpec). This is the "edge / feature-flag" cluster:
# minimal dims, GQA ratios, and every feature-flag path (qq_bias, fp8 KV,
# register-PV, i64 KV addressing, the transposed 32x32 + grouped-KV2 softmax
# stack, early-V schedule, and the fast paged-KV descriptor).
from rocke.instances.gfx950.attention_tiled_2d import (
    UnifiedAttention2DTiledSpec,
    build_unified_attention_2d_tiled,
)
from _emit_common import run_emit


_CONFIGS = {
    # --- idx0-4: minimal dims, block_size=16, head_size {64,128,256}, GQA ratios
    0: dict(
        head_size=64,
        block_size=16,
        num_query_heads=1,
        num_kv_heads=1,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
    ),
    1: dict(
        head_size=128,
        block_size=16,
        num_query_heads=1,
        num_kv_heads=1,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
    ),
    2: dict(
        head_size=256,
        block_size=16,
        num_query_heads=1,
        num_kv_heads=1,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
    ),
    3: dict(
        head_size=64,
        block_size=16,
        num_query_heads=16,
        num_kv_heads=1,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
    ),
    4: dict(
        head_size=64,
        block_size=16,
        num_query_heads=2,
        num_kv_heads=1,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
    ),
    # --- idx5-14: baseline dtype / mask-feature / head-size / block-size variety
    5: dict(
        head_size=64,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
    ),
    6: dict(
        head_size=64,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="fp16",
        use_sinks=True,
        sliding_window=2048,
        has_softcap=True,
    ),
    7: dict(
        head_size=64,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=True,
        sliding_window=1,
        has_softcap=False,
    ),
    8: dict(
        head_size=128,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="fp16",
        use_sinks=True,
        sliding_window=0,
        has_softcap=True,
    ),
    9: dict(
        head_size=256,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
    ),
    10: dict(
        head_size=64,
        block_size=64,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
    ),
    11: dict(
        head_size=64,
        block_size=32,
        num_query_heads=7,
        num_kv_heads=7,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
    ),
    12: dict(
        head_size=64,
        block_size=32,
        num_query_heads=64,
        num_kv_heads=8,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
    ),
    13: dict(
        head_size=64,
        block_size=32,
        num_query_heads=40,
        num_kv_heads=8,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
    ),
    14: dict(
        head_size=64,
        block_size=32,
        num_query_heads=128,
        num_kv_heads=1,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
    ),
    # --- idx15: QQ-bias feature flag
    15: dict(
        head_size=64,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        use_qq_bias=True,
    ),
    # --- idx16,17: ALiBi / composite mask features
    16: dict(
        head_size=64,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        use_alibi=True,
    ),
    17: dict(
        head_size=64,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="fp16",
        use_sinks=True,
        sliding_window=512,
        has_softcap=True,
        use_alibi=True,
        use_qq_bias=True,
    ),
    # --- idx18: num_warps=8 (BLOCK_M=128), no tile_size
    18: dict(
        head_size=64,
        block_size=64,
        num_query_heads=64,
        num_kv_heads=8,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        num_warps=8,
    ),
    # --- idx19-26: num_warps / tile_size / waves_per_eu / num_seqs variety
    19: dict(
        head_size=64,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        num_warps=2,
    ),
    20: dict(
        head_size=64,
        block_size=32,
        num_query_heads=64,
        num_kv_heads=8,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        num_warps=4,
    ),
    21: dict(
        head_size=64,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        tile_size=64,
    ),
    22: dict(
        head_size=64,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        tile_size=128,
    ),
    23: dict(
        head_size=128,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="fp16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        num_warps=2,
        tile_size=128,
    ),
    24: dict(
        head_size=64,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        waves_per_eu=2,
    ),
    25: dict(
        head_size=64,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        num_seqs=1,
    ),
    26: dict(
        head_size=64,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        num_seqs=257,
    ),
    # --- idx27: fp8 KV cache with native fp8 PV MFMA
    27: dict(
        head_size=64,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        kv_storage_dtype="fp8e4m3",
        use_fp8_mfma_pv=True,
    ),
    # --- idx28: 64-bit paged-KV addressing
    28: dict(
        head_size=64,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        use_i64_kv_addr=True,
    ),
    # --- idx29: register-PV bf16 path
    29: dict(
        head_size=64,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        use_register_pv=True,
    ),
    # --- idx30-32: fp8 KV (dequant), fp8 QK MFMA, mfma_32x32 base
    30: dict(
        head_size=64,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        kv_storage_dtype="fp8e4m3",
    ),
    31: dict(
        head_size=64,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        kv_storage_dtype="fp8e4m3",
        use_fp8_mfma_qk=True,
    ),
    32: dict(
        head_size=128,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="fp16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        use_mfma_32x32=True,
        block_m_per_warp=32,
        tile_size=64,
    ),
    # --- idx33-35: transposed 32x32 + scalar-state + invariant-hoist + mask-once
    #               + grouped-KV2 softmax stack (bf16, BLOCK_M=128 warp slice)
    33: dict(
        head_size=64,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        use_mfma_32x32=True,
        use_transposed_qk_32x32=True,
        use_transposed_scalar_state=True,
        use_transposed_invariant_hoist=True,
        use_transposed_mask_once=True,
        use_grouped_kv2_softmax=True,
        block_m_per_warp=32,
        tile_size=64,
    ),
    34: dict(
        head_size=128,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        use_mfma_32x32=True,
        use_transposed_qk_32x32=True,
        use_transposed_scalar_state=True,
        use_transposed_invariant_hoist=True,
        use_transposed_mask_once=True,
        use_grouped_kv2_softmax=True,
        block_m_per_warp=32,
        tile_size=64,
    ),
    35: dict(
        head_size=64,
        block_size=32,
        num_query_heads=64,
        num_kv_heads=8,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        use_mfma_32x32=True,
        use_transposed_qk_32x32=True,
        use_transposed_scalar_state=True,
        use_transposed_invariant_hoist=True,
        use_transposed_mask_once=True,
        use_grouped_kv2_softmax=True,
        num_warps=4,
        block_m_per_warp=32,
        tile_size=64,
    ),
    # --- idx36: early-V schedule
    36: dict(
        head_size=64,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        use_early_v_schedule=True,
    ),
    # --- idx37: fast paged-KV descriptor (bf16 h64kv8 HD=64 BS=32 T=64 nw=4)
    37: dict(
        head_size=64,
        block_size=32,
        num_query_heads=64,
        num_kv_heads=8,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        num_warps=4,
        block_m_per_warp=16,
        tile_size=64,
        use_fast_paged_kv_desc=True,
    ),
    # --- idx38-41: transposed 32x32 + half-local-PV (hlpv) reschedule stack.
    #     hlpv requires use_transposed_qk_32x32; covers d64/d128 x fp16/bf16.
    38: dict(
        head_size=64,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        use_mfma_32x32=True,
        use_transposed_qk_32x32=True,
        use_transposed_half_local_pv=True,
        block_m_per_warp=32,
        tile_size=64,
    ),
    39: dict(
        head_size=128,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        use_mfma_32x32=True,
        use_transposed_qk_32x32=True,
        use_transposed_half_local_pv=True,
        block_m_per_warp=32,
        tile_size=64,
    ),
    40: dict(
        head_size=64,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="fp16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        use_mfma_32x32=True,
        use_transposed_qk_32x32=True,
        use_transposed_half_local_pv=True,
        block_m_per_warp=32,
        tile_size=64,
    ),
    41: dict(
        head_size=128,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="fp16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        use_mfma_32x32=True,
        use_transposed_qk_32x32=True,
        use_transposed_half_local_pv=True,
        block_m_per_warp=32,
        tile_size=64,
    ),
    # --- idx42: exact provider build_sdpa_tiled hlpv shape (combo multi_batch
    #     GQA-8 h64kv8 bf16: the shape the provider prefill path routes to). ---
    42: dict(
        head_size=64,
        block_size=32,
        num_query_heads=64,
        num_kv_heads=8,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        num_seqs=2,
        num_warps=4,
        use_mfma_32x32=True,
        use_transposed_qk_32x32=True,
        use_transposed_scalar_state=True,
        use_transposed_mask_once=True,
        use_transposed_half_local_pv=True,
        block_m_per_warp=32,
        tile_size=64,
    ),
    # --- idx43-49: gfx950 PRODUCTION combo knobs the selector
    #     (_tiled_spec_from_problem gfx950 path) sets but the gate never
    #     sampled: the FULL no-SW combo with use_transposed_mask_limit ON
    #     (idx33-35 left it OFF), use_v_double_buffer, use_early_v_schedule
    #     stacked on the mask-limit combo, and use_grouped_kv2_softmax on the
    #     main 2D builder (previously only in the fastkv_regp variant). ---
    # idx43: FULL no-SW combo incl. use_transposed_mask_limit + skip_legacy +
    #        hlpv + fast_paged_kv (the bf16 GQA-8 d64 production combo).
    43: dict(
        head_size=64,
        block_size=32,
        num_query_heads=64,
        num_kv_heads=8,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        num_warps=4,
        block_m_per_warp=32,
        tile_size=64,
        use_mfma_32x32=True,
        use_transposed_qk_32x32=True,
        use_transposed_scalar_state=True,
        use_transposed_invariant_hoist=True,
        use_transposed_mask_once=True,
        use_transposed_mask_limit=True,
        use_mfma32_skip_legacy_qreg=True,
        use_transposed_half_local_pv=True,
        use_fast_paged_kv_desc=True,
    ),
    # idx44: d128 full mask-limit combo (no fast_paged_kv; HD=128).
    44: dict(
        head_size=128,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        num_warps=4,
        block_m_per_warp=32,
        tile_size=64,
        use_mfma_32x32=True,
        use_transposed_qk_32x32=True,
        use_transposed_scalar_state=True,
        use_transposed_invariant_hoist=True,
        use_transposed_mask_once=True,
        use_transposed_mask_limit=True,
        use_mfma32_skip_legacy_qreg=True,
        use_transposed_half_local_pv=True,
    ),
    # idx45: fp16 full mask-limit combo.
    45: dict(
        head_size=64,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="fp16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        num_warps=4,
        block_m_per_warp=32,
        tile_size=64,
        use_mfma_32x32=True,
        use_transposed_qk_32x32=True,
        use_transposed_scalar_state=True,
        use_transposed_invariant_hoist=True,
        use_transposed_mask_once=True,
        use_transposed_mask_limit=True,
        use_mfma32_skip_legacy_qreg=True,
        use_transposed_half_local_pv=True,
    ),
    # idx46: mask-limit combo with invariant-hoist + skip_legacy but WITHOUT
    #        half_local_pv (the plain-PV transposed combo the multi-batch
    #        selector picks when hlpv regresses), num_warps=2 BLOCK_M=64.
    46: dict(
        head_size=64,
        block_size=32,
        num_query_heads=32,
        num_kv_heads=32,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        num_warps=2,
        block_m_per_warp=32,
        tile_size=64,
        use_mfma_32x32=True,
        use_transposed_qk_32x32=True,
        use_transposed_scalar_state=True,
        use_transposed_invariant_hoist=True,
        use_transposed_mask_once=True,
        use_transposed_mask_limit=True,
        use_mfma32_skip_legacy_qreg=True,
    ),
    # idx47: use_early_v_schedule on the mask-limit combo (long-prefill
    #        single-batch combo V-prefetch winner; mutually exclusive with
    #        v_double_buffer).
    47: dict(
        head_size=64,
        block_size=32,
        num_query_heads=64,
        num_kv_heads=8,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        num_warps=4,
        block_m_per_warp=32,
        tile_size=64,
        use_mfma_32x32=True,
        use_transposed_qk_32x32=True,
        use_transposed_scalar_state=True,
        use_transposed_mask_once=True,
        use_transposed_mask_limit=True,
        use_transposed_half_local_pv=True,
        use_early_v_schedule=True,
    ),
    # idx48: use_grouped_kv2_softmax on the MAIN 2D builder (the bf16
    #        transposed R4 grouped-KV2 path; gate previously only sampled it
    #        in the fastkv_regp variant).
    48: dict(
        head_size=64,
        block_size=32,
        num_query_heads=64,
        num_kv_heads=8,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        num_warps=4,
        block_m_per_warp=32,
        tile_size=64,
        use_mfma_32x32=True,
        use_transposed_qk_32x32=True,
        use_transposed_scalar_state=True,
        use_grouped_kv2_softmax=True,
    ),
    # idx49: single-batch (num_seqs=1) full mask-limit combo with early_v
    #        schedule stacked (the _enable_single_batch_combo long-prefill
    #        production winner: mask-limit VALU + hlpv + early-V issue).
    49: dict(
        head_size=64,
        block_size=32,
        num_query_heads=64,
        num_kv_heads=8,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        num_seqs=1,
        num_warps=4,
        block_m_per_warp=32,
        tile_size=64,
        use_mfma_32x32=True,
        use_transposed_qk_32x32=True,
        use_transposed_scalar_state=True,
        use_transposed_invariant_hoist=True,
        use_transposed_mask_once=True,
        use_transposed_mask_limit=True,
        use_mfma32_skip_legacy_qreg=True,
        use_transposed_half_local_pv=True,
        use_early_v_schedule=True,
    ),
    # idx50: lever-3 sched_barrier (#51/#57) on the single-batch d128 combo
    # (num_warps=1, the cohort the dispatcher auto-enables it for). Exercises the
    # rocke_b_sched_barrier emit point in the C twin's transposed-QK path.
    50: dict(
        head_size=128,
        block_size=32,
        num_query_heads=64,
        num_kv_heads=8,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        num_seqs=1,
        num_warps=1,
        block_m_per_warp=32,
        tile_size=64,
        use_mfma_32x32=True,
        use_transposed_qk_32x32=True,
        use_transposed_scalar_state=True,
        use_transposed_invariant_hoist=True,
        use_transposed_mask_once=True,
        use_transposed_mask_limit=True,
        use_mfma32_skip_legacy_qreg=True,
        use_transposed_half_local_pv=True,
        use_sched_barrier=True,
    ),
    # idx51: #66 small-tile d128 2-WG/CU win path -- the full single-batch d128
    # combo with tile_size=32 (== block_size, one paged block per iter) at
    # num_warps=2. This is the geometry that halves K_lds/V_lds (48->24 KB) and
    # drops VGPR (229->173) -> 2 WG/CU at d128. It uses NO new code path (just a
    # smaller tile_size on the existing combo), so it MUST be C/Python identical.
    51: dict(
        head_size=128,
        block_size=32,
        num_query_heads=64,
        num_kv_heads=8,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        num_seqs=1,
        num_warps=2,
        block_m_per_warp=32,
        tile_size=32,
        use_mfma_32x32=True,
        use_transposed_qk_32x32=True,
        use_transposed_scalar_state=True,
        use_transposed_invariant_hoist=True,
        use_transposed_mask_once=True,
        use_transposed_mask_limit=True,
        use_mfma32_skip_legacy_qreg=True,
        use_transposed_half_local_pv=True,
    ),
    # idx52 REMOVED: it exercised the deep K prefetch ring (kv_ring_depth=3), a
    # Python-only EXPERIMENTAL lever that the production selector NEVER sets
    # (kv_ring_depth is not referenced in attention_unified.py) and that the
    # gfx950 C twin rejects by design (ROCKE_ERR_NOTIMPL). The byte-identity gate
    # compares EMITTED IR for the production-reachable surface; a config one
    # engine cannot emit is intrinsically asymmetric (C reject vs Python emit)
    # and does not belong here. The C-side reject guard remains in
    # attention_tiled_2d_public_entry_glue.cpp; ring-3 was superseded by the
    # use_softmax_mfma_interleave lever and is not a production path.
    # idx52 (renumbered from 53 after the ring-3 config was removed; kept
    # contiguous so the gate's shared-end-of-range detection doesn't stop early
    # on a hole): #69 K single-buffer at T=64 -- the d128 long-context 2-WG/CU
    # win. The full single-batch d128 combo with tile_size=64 (== 2*block_size)
    # AND use_k_single_buffer=True. K_lds collapses 2->1 slot (32->16 KB) so
    # total LDS is 32 KB -> 2 WG/CU at the LARGER tile (better S4096 amortisation
    # than the idx51 T=32 pick). The next-K prefetch is re-issued AFTER the
    # PV-wait s_barrier (all QK reads drained) so the single slot cannot
    # WAR-race. This IS ported to the gfx950 C twin (K_BUFS=1 + deferred K
    # issue), so it MUST be C/Python byte-identical.
    52: dict(
        head_size=128,
        block_size=32,
        num_query_heads=64,
        num_kv_heads=8,
        dtype="bf16",
        use_sinks=False,
        sliding_window=0,
        has_softcap=False,
        num_seqs=1,
        num_warps=2,
        block_m_per_warp=32,
        tile_size=64,
        use_k_single_buffer=True,
        use_mfma_32x32=True,
        use_transposed_qk_32x32=True,
        use_transposed_scalar_state=True,
        use_transposed_invariant_hoist=True,
        use_transposed_mask_once=True,
        use_transposed_mask_limit=True,
        use_mfma32_skip_legacy_qreg=True,
        use_transposed_half_local_pv=True,
    ),
}


def _spec(idx: int) -> UnifiedAttention2DTiledSpec:
    if idx not in _CONFIGS:
        raise SystemExit(f"unknown config index {idx}")
    return UnifiedAttention2DTiledSpec(**_CONFIGS[idx])


def main() -> int:
    return run_emit(
        _spec,
        build_unified_attention_2d_tiled,
        usage="usage: gfx950_attention_tiled_2d_emit.py <config_index>\n",
    )


if __name__ == "__main__":
    raise SystemExit(main())
