// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_DATATYPES_HIPDNN_FLATBUFFERS_SDK_DATA_OBJECTS_H_
#define FLATBUFFERS_GENERATED_DATATYPES_HIPDNN_FLATBUFFERS_SDK_DATA_OBJECTS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");


namespace hipdnn_flatbuffers_sdk {
namespace data_objects {

enum class DataType : int8_t {
  UNSET = 0,
  FLOAT = 1,
  HALF = 2,
  BFLOAT16 = 3,
  DOUBLE = 4,
  UINT8 = 5,
  INT32 = 6,
  INT8 = 7,
  FP8_E4M3 = 8,
  FP8_E5M2 = 9,
  FP8_E8M0 = 10,
  FP4_E2M1 = 11,
  FP6_E2M3 = 12,
  FP6_E3M2 = 13,
  INT4 = 14,
  INT64 = 15,
  BOOLEAN = 16,
  FP8_E4M3_FNUZ = 17,
  FP8_E5M2_FNUZ = 18,
  MIN = UNSET,
  MAX = FP8_E5M2_FNUZ
};

inline const DataType (&EnumValuesDataType())[19] {
  static const DataType values[] = {
    DataType::UNSET,
    DataType::FLOAT,
    DataType::HALF,
    DataType::BFLOAT16,
    DataType::DOUBLE,
    DataType::UINT8,
    DataType::INT32,
    DataType::INT8,
    DataType::FP8_E4M3,
    DataType::FP8_E5M2,
    DataType::FP8_E8M0,
    DataType::FP4_E2M1,
    DataType::FP6_E2M3,
    DataType::FP6_E3M2,
    DataType::INT4,
    DataType::INT64,
    DataType::BOOLEAN,
    DataType::FP8_E4M3_FNUZ,
    DataType::FP8_E5M2_FNUZ
  };
  return values;
}

inline const char * const *EnumNamesDataType() {
  static const char * const names[20] = {
    "UNSET",
    "FLOAT",
    "HALF",
    "BFLOAT16",
    "DOUBLE",
    "UINT8",
    "INT32",
    "INT8",
    "FP8_E4M3",
    "FP8_E5M2",
    "FP8_E8M0",
    "FP4_E2M1",
    "FP6_E2M3",
    "FP6_E3M2",
    "INT4",
    "INT64",
    "BOOLEAN",
    "FP8_E4M3_FNUZ",
    "FP8_E5M2_FNUZ",
    nullptr
  };
  return names;
}

inline const char *EnumNameDataType(DataType e) {
  if (::flatbuffers::IsOutRange(e, DataType::UNSET, DataType::FP8_E5M2_FNUZ)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesDataType()[index];
}

}  // namespace data_objects
}  // namespace hipdnn_flatbuffers_sdk

#endif  // FLATBUFFERS_GENERATED_DATATYPES_HIPDNN_FLATBUFFERS_SDK_DATA_OBJECTS_H_
