// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_EXECUTIONPLAN_HIPDNN_FLATBUFFERS_SDK_DATA_OBJECTS_H_
#define FLATBUFFERS_GENERATED_EXECUTIONPLAN_HIPDNN_FLATBUFFERS_SDK_DATA_OBJECTS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

namespace hipdnn_flatbuffers_sdk {
namespace data_objects {

struct SerializedExecutionPlan;
struct SerializedExecutionPlanBuilder;
struct SerializedExecutionPlanT;

bool operator==(const SerializedExecutionPlanT &lhs, const SerializedExecutionPlanT &rhs);
bool operator!=(const SerializedExecutionPlanT &lhs, const SerializedExecutionPlanT &rhs);

struct SerializedExecutionPlanT : public ::flatbuffers::NativeTable {
  typedef SerializedExecutionPlan TableType;
  uint32_t version = 0;
  int64_t engine_id = 0;
  int64_t workspace_size = 0;
  std::vector<int64_t> tensor_uids{};
  std::vector<uint8_t> plugin_payload{};
  bool is_override_shape_enabled = false;
};

struct SerializedExecutionPlan FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SerializedExecutionPlanT NativeTableType;
  typedef SerializedExecutionPlanBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VERSION = 4,
    VT_ENGINE_ID = 6,
    VT_WORKSPACE_SIZE = 8,
    VT_TENSOR_UIDS = 10,
    VT_PLUGIN_PAYLOAD = 12,
    VT_IS_OVERRIDE_SHAPE_ENABLED = 14
  };
  uint32_t version() const {
    return GetField<uint32_t>(VT_VERSION, 0);
  }
  bool mutate_version(uint32_t _version = 0) {
    return SetField<uint32_t>(VT_VERSION, _version, 0);
  }
  int64_t engine_id() const {
    return GetField<int64_t>(VT_ENGINE_ID, 0);
  }
  bool mutate_engine_id(int64_t _engine_id = 0) {
    return SetField<int64_t>(VT_ENGINE_ID, _engine_id, 0);
  }
  int64_t workspace_size() const {
    return GetField<int64_t>(VT_WORKSPACE_SIZE, 0);
  }
  bool mutate_workspace_size(int64_t _workspace_size = 0) {
    return SetField<int64_t>(VT_WORKSPACE_SIZE, _workspace_size, 0);
  }
  const ::flatbuffers::Vector<int64_t> *tensor_uids() const {
    return GetPointer<const ::flatbuffers::Vector<int64_t> *>(VT_TENSOR_UIDS);
  }
  ::flatbuffers::Vector<int64_t> *mutable_tensor_uids() {
    return GetPointer<::flatbuffers::Vector<int64_t> *>(VT_TENSOR_UIDS);
  }
  const ::flatbuffers::Vector<uint8_t> *plugin_payload() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_PLUGIN_PAYLOAD);
  }
  ::flatbuffers::Vector<uint8_t> *mutable_plugin_payload() {
    return GetPointer<::flatbuffers::Vector<uint8_t> *>(VT_PLUGIN_PAYLOAD);
  }
  bool is_override_shape_enabled() const {
    return GetField<uint8_t>(VT_IS_OVERRIDE_SHAPE_ENABLED, 0) != 0;
  }
  bool mutate_is_override_shape_enabled(bool _is_override_shape_enabled = 0) {
    return SetField<uint8_t>(VT_IS_OVERRIDE_SHAPE_ENABLED, static_cast<uint8_t>(_is_override_shape_enabled), 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_VERSION, 4) &&
           VerifyField<int64_t>(verifier, VT_ENGINE_ID, 8) &&
           VerifyField<int64_t>(verifier, VT_WORKSPACE_SIZE, 8) &&
           VerifyOffset(verifier, VT_TENSOR_UIDS) &&
           verifier.VerifyVector(tensor_uids()) &&
           VerifyOffset(verifier, VT_PLUGIN_PAYLOAD) &&
           verifier.VerifyVector(plugin_payload()) &&
           VerifyField<uint8_t>(verifier, VT_IS_OVERRIDE_SHAPE_ENABLED, 1) &&
           verifier.EndTable();
  }
  SerializedExecutionPlanT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(SerializedExecutionPlanT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<SerializedExecutionPlan> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SerializedExecutionPlanT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct SerializedExecutionPlanBuilder {
  typedef SerializedExecutionPlan Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_version(uint32_t version) {
    fbb_.AddElement<uint32_t>(SerializedExecutionPlan::VT_VERSION, version, 0);
  }
  void add_engine_id(int64_t engine_id) {
    fbb_.AddElement<int64_t>(SerializedExecutionPlan::VT_ENGINE_ID, engine_id, 0);
  }
  void add_workspace_size(int64_t workspace_size) {
    fbb_.AddElement<int64_t>(SerializedExecutionPlan::VT_WORKSPACE_SIZE, workspace_size, 0);
  }
  void add_tensor_uids(::flatbuffers::Offset<::flatbuffers::Vector<int64_t>> tensor_uids) {
    fbb_.AddOffset(SerializedExecutionPlan::VT_TENSOR_UIDS, tensor_uids);
  }
  void add_plugin_payload(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> plugin_payload) {
    fbb_.AddOffset(SerializedExecutionPlan::VT_PLUGIN_PAYLOAD, plugin_payload);
  }
  void add_is_override_shape_enabled(bool is_override_shape_enabled) {
    fbb_.AddElement<uint8_t>(SerializedExecutionPlan::VT_IS_OVERRIDE_SHAPE_ENABLED, static_cast<uint8_t>(is_override_shape_enabled), 0);
  }
  explicit SerializedExecutionPlanBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SerializedExecutionPlan> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SerializedExecutionPlan>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SerializedExecutionPlan> CreateSerializedExecutionPlan(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t version = 0,
    int64_t engine_id = 0,
    int64_t workspace_size = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<int64_t>> tensor_uids = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> plugin_payload = 0,
    bool is_override_shape_enabled = false) {
  SerializedExecutionPlanBuilder builder_(_fbb);
  builder_.add_workspace_size(workspace_size);
  builder_.add_engine_id(engine_id);
  builder_.add_plugin_payload(plugin_payload);
  builder_.add_tensor_uids(tensor_uids);
  builder_.add_version(version);
  builder_.add_is_override_shape_enabled(is_override_shape_enabled);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SerializedExecutionPlan> CreateSerializedExecutionPlanDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t version = 0,
    int64_t engine_id = 0,
    int64_t workspace_size = 0,
    const std::vector<int64_t> *tensor_uids = nullptr,
    const std::vector<uint8_t> *plugin_payload = nullptr,
    bool is_override_shape_enabled = false) {
  auto tensor_uids__ = tensor_uids ? _fbb.CreateVector<int64_t>(*tensor_uids) : 0;
  auto plugin_payload__ = plugin_payload ? _fbb.CreateVector<uint8_t>(*plugin_payload) : 0;
  return hipdnn_flatbuffers_sdk::data_objects::CreateSerializedExecutionPlan(
      _fbb,
      version,
      engine_id,
      workspace_size,
      tensor_uids__,
      plugin_payload__,
      is_override_shape_enabled);
}

::flatbuffers::Offset<SerializedExecutionPlan> CreateSerializedExecutionPlan(::flatbuffers::FlatBufferBuilder &_fbb, const SerializedExecutionPlanT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);


inline bool operator==(const SerializedExecutionPlanT &lhs, const SerializedExecutionPlanT &rhs) {
  return
      (lhs.version == rhs.version) &&
      (lhs.engine_id == rhs.engine_id) &&
      (lhs.workspace_size == rhs.workspace_size) &&
      (lhs.tensor_uids == rhs.tensor_uids) &&
      (lhs.plugin_payload == rhs.plugin_payload) &&
      (lhs.is_override_shape_enabled == rhs.is_override_shape_enabled);
}

inline bool operator!=(const SerializedExecutionPlanT &lhs, const SerializedExecutionPlanT &rhs) {
    return !(lhs == rhs);
}


inline SerializedExecutionPlanT *SerializedExecutionPlan::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<SerializedExecutionPlanT>(new SerializedExecutionPlanT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void SerializedExecutionPlan::UnPackTo(SerializedExecutionPlanT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = version(); _o->version = _e; }
  { auto _e = engine_id(); _o->engine_id = _e; }
  { auto _e = workspace_size(); _o->workspace_size = _e; }
  { auto _e = tensor_uids(); if (_e) { _o->tensor_uids.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->tensor_uids[_i] = _e->Get(_i); } } else { _o->tensor_uids.resize(0); } }
  { auto _e = plugin_payload(); if (_e) { _o->plugin_payload.resize(_e->size()); std::copy(_e->begin(), _e->end(), _o->plugin_payload.begin()); } }
  { auto _e = is_override_shape_enabled(); _o->is_override_shape_enabled = _e; }
}

inline ::flatbuffers::Offset<SerializedExecutionPlan> SerializedExecutionPlan::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SerializedExecutionPlanT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateSerializedExecutionPlan(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<SerializedExecutionPlan> CreateSerializedExecutionPlan(::flatbuffers::FlatBufferBuilder &_fbb, const SerializedExecutionPlanT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const SerializedExecutionPlanT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _version = _o->version;
  auto _engine_id = _o->engine_id;
  auto _workspace_size = _o->workspace_size;
  auto _tensor_uids = _o->tensor_uids.size() ? _fbb.CreateVector(_o->tensor_uids) : 0;
  auto _plugin_payload = _o->plugin_payload.size() ? _fbb.CreateVector(_o->plugin_payload) : 0;
  auto _is_override_shape_enabled = _o->is_override_shape_enabled;
  return hipdnn_flatbuffers_sdk::data_objects::CreateSerializedExecutionPlan(
      _fbb,
      _version,
      _engine_id,
      _workspace_size,
      _tensor_uids,
      _plugin_payload,
      _is_override_shape_enabled);
}

inline const hipdnn_flatbuffers_sdk::data_objects::SerializedExecutionPlan *GetSerializedExecutionPlan(const void *buf) {
  return ::flatbuffers::GetRoot<hipdnn_flatbuffers_sdk::data_objects::SerializedExecutionPlan>(buf);
}

inline const hipdnn_flatbuffers_sdk::data_objects::SerializedExecutionPlan *GetSizePrefixedSerializedExecutionPlan(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<hipdnn_flatbuffers_sdk::data_objects::SerializedExecutionPlan>(buf);
}

inline SerializedExecutionPlan *GetMutableSerializedExecutionPlan(void *buf) {
  return ::flatbuffers::GetMutableRoot<SerializedExecutionPlan>(buf);
}

inline hipdnn_flatbuffers_sdk::data_objects::SerializedExecutionPlan *GetMutableSizePrefixedSerializedExecutionPlan(void *buf) {
  return ::flatbuffers::GetMutableSizePrefixedRoot<hipdnn_flatbuffers_sdk::data_objects::SerializedExecutionPlan>(buf);
}

inline bool VerifySerializedExecutionPlanBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<hipdnn_flatbuffers_sdk::data_objects::SerializedExecutionPlan>(nullptr);
}

inline bool VerifySizePrefixedSerializedExecutionPlanBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<hipdnn_flatbuffers_sdk::data_objects::SerializedExecutionPlan>(nullptr);
}

inline void FinishSerializedExecutionPlanBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<hipdnn_flatbuffers_sdk::data_objects::SerializedExecutionPlan> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedSerializedExecutionPlanBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<hipdnn_flatbuffers_sdk::data_objects::SerializedExecutionPlan> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<hipdnn_flatbuffers_sdk::data_objects::SerializedExecutionPlanT> UnPackSerializedExecutionPlan(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<hipdnn_flatbuffers_sdk::data_objects::SerializedExecutionPlanT>(GetSerializedExecutionPlan(buf)->UnPack(res));
}

inline std::unique_ptr<hipdnn_flatbuffers_sdk::data_objects::SerializedExecutionPlanT> UnPackSizePrefixedSerializedExecutionPlan(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<hipdnn_flatbuffers_sdk::data_objects::SerializedExecutionPlanT>(GetSizePrefixedSerializedExecutionPlan(buf)->UnPack(res));
}

}  // namespace data_objects
}  // namespace hipdnn_flatbuffers_sdk

#endif  // FLATBUFFERS_GENERATED_EXECUTIONPLAN_HIPDNN_FLATBUFFERS_SDK_DATA_OBJECTS_H_
