// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SERIALIZEDGRAPHANDPLAN_HIPDNN_FLATBUFFERS_SDK_DATA_OBJECTS_H_
#define FLATBUFFERS_GENERATED_SERIALIZEDGRAPHANDPLAN_HIPDNN_FLATBUFFERS_SDK_DATA_OBJECTS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

namespace hipdnn_flatbuffers_sdk {
namespace data_objects {

struct SerializedGraphAndPlan;
struct SerializedGraphAndPlanBuilder;
struct SerializedGraphAndPlanT;

bool operator==(const SerializedGraphAndPlanT &lhs, const SerializedGraphAndPlanT &rhs);
bool operator!=(const SerializedGraphAndPlanT &lhs, const SerializedGraphAndPlanT &rhs);

struct SerializedGraphAndPlanT : public ::flatbuffers::NativeTable {
  typedef SerializedGraphAndPlan TableType;
  std::vector<uint8_t> graph_blob{};
  std::vector<uint8_t> plan_blob{};
};

struct SerializedGraphAndPlan FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SerializedGraphAndPlanT NativeTableType;
  typedef SerializedGraphAndPlanBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_GRAPH_BLOB = 4,
    VT_PLAN_BLOB = 6
  };
  const ::flatbuffers::Vector<uint8_t> *graph_blob() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_GRAPH_BLOB);
  }
  ::flatbuffers::Vector<uint8_t> *mutable_graph_blob() {
    return GetPointer<::flatbuffers::Vector<uint8_t> *>(VT_GRAPH_BLOB);
  }
  const ::flatbuffers::Vector<uint8_t> *plan_blob() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_PLAN_BLOB);
  }
  ::flatbuffers::Vector<uint8_t> *mutable_plan_blob() {
    return GetPointer<::flatbuffers::Vector<uint8_t> *>(VT_PLAN_BLOB);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_GRAPH_BLOB) &&
           verifier.VerifyVector(graph_blob()) &&
           VerifyOffset(verifier, VT_PLAN_BLOB) &&
           verifier.VerifyVector(plan_blob()) &&
           verifier.EndTable();
  }
  SerializedGraphAndPlanT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(SerializedGraphAndPlanT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<SerializedGraphAndPlan> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SerializedGraphAndPlanT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct SerializedGraphAndPlanBuilder {
  typedef SerializedGraphAndPlan Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_graph_blob(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> graph_blob) {
    fbb_.AddOffset(SerializedGraphAndPlan::VT_GRAPH_BLOB, graph_blob);
  }
  void add_plan_blob(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> plan_blob) {
    fbb_.AddOffset(SerializedGraphAndPlan::VT_PLAN_BLOB, plan_blob);
  }
  explicit SerializedGraphAndPlanBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SerializedGraphAndPlan> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SerializedGraphAndPlan>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SerializedGraphAndPlan> CreateSerializedGraphAndPlan(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> graph_blob = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> plan_blob = 0) {
  SerializedGraphAndPlanBuilder builder_(_fbb);
  builder_.add_plan_blob(plan_blob);
  builder_.add_graph_blob(graph_blob);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SerializedGraphAndPlan> CreateSerializedGraphAndPlanDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint8_t> *graph_blob = nullptr,
    const std::vector<uint8_t> *plan_blob = nullptr) {
  if (graph_blob) { _fbb.ForceVectorAlignment(graph_blob->size(), sizeof(uint8_t), 8); }
  auto graph_blob__ = graph_blob ? _fbb.CreateVector<uint8_t>(*graph_blob) : 0;
  if (plan_blob) { _fbb.ForceVectorAlignment(plan_blob->size(), sizeof(uint8_t), 8); }
  auto plan_blob__ = plan_blob ? _fbb.CreateVector<uint8_t>(*plan_blob) : 0;
  return hipdnn_flatbuffers_sdk::data_objects::CreateSerializedGraphAndPlan(
      _fbb,
      graph_blob__,
      plan_blob__);
}

::flatbuffers::Offset<SerializedGraphAndPlan> CreateSerializedGraphAndPlan(::flatbuffers::FlatBufferBuilder &_fbb, const SerializedGraphAndPlanT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);


inline bool operator==(const SerializedGraphAndPlanT &lhs, const SerializedGraphAndPlanT &rhs) {
  return
      (lhs.graph_blob == rhs.graph_blob) &&
      (lhs.plan_blob == rhs.plan_blob);
}

inline bool operator!=(const SerializedGraphAndPlanT &lhs, const SerializedGraphAndPlanT &rhs) {
    return !(lhs == rhs);
}


inline SerializedGraphAndPlanT *SerializedGraphAndPlan::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<SerializedGraphAndPlanT>(new SerializedGraphAndPlanT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void SerializedGraphAndPlan::UnPackTo(SerializedGraphAndPlanT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = graph_blob(); if (_e) { _o->graph_blob.resize(_e->size()); std::copy(_e->begin(), _e->end(), _o->graph_blob.begin()); } }
  { auto _e = plan_blob(); if (_e) { _o->plan_blob.resize(_e->size()); std::copy(_e->begin(), _e->end(), _o->plan_blob.begin()); } }
}

inline ::flatbuffers::Offset<SerializedGraphAndPlan> SerializedGraphAndPlan::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SerializedGraphAndPlanT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateSerializedGraphAndPlan(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<SerializedGraphAndPlan> CreateSerializedGraphAndPlan(::flatbuffers::FlatBufferBuilder &_fbb, const SerializedGraphAndPlanT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const SerializedGraphAndPlanT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  _fbb.ForceVectorAlignment(_o->graph_blob.size(), sizeof(uint8_t), 8);
  auto _graph_blob = _o->graph_blob.size() ? _fbb.CreateVector(_o->graph_blob) : 0;
  _fbb.ForceVectorAlignment(_o->plan_blob.size(), sizeof(uint8_t), 8);
  auto _plan_blob = _o->plan_blob.size() ? _fbb.CreateVector(_o->plan_blob) : 0;
  return hipdnn_flatbuffers_sdk::data_objects::CreateSerializedGraphAndPlan(
      _fbb,
      _graph_blob,
      _plan_blob);
}

inline const hipdnn_flatbuffers_sdk::data_objects::SerializedGraphAndPlan *GetSerializedGraphAndPlan(const void *buf) {
  return ::flatbuffers::GetRoot<hipdnn_flatbuffers_sdk::data_objects::SerializedGraphAndPlan>(buf);
}

inline const hipdnn_flatbuffers_sdk::data_objects::SerializedGraphAndPlan *GetSizePrefixedSerializedGraphAndPlan(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<hipdnn_flatbuffers_sdk::data_objects::SerializedGraphAndPlan>(buf);
}

inline SerializedGraphAndPlan *GetMutableSerializedGraphAndPlan(void *buf) {
  return ::flatbuffers::GetMutableRoot<SerializedGraphAndPlan>(buf);
}

inline hipdnn_flatbuffers_sdk::data_objects::SerializedGraphAndPlan *GetMutableSizePrefixedSerializedGraphAndPlan(void *buf) {
  return ::flatbuffers::GetMutableSizePrefixedRoot<hipdnn_flatbuffers_sdk::data_objects::SerializedGraphAndPlan>(buf);
}

inline const char *SerializedGraphAndPlanIdentifier() {
  return "HDGP";
}

inline bool SerializedGraphAndPlanBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, SerializedGraphAndPlanIdentifier());
}

inline bool SizePrefixedSerializedGraphAndPlanBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, SerializedGraphAndPlanIdentifier(), true);
}

inline bool VerifySerializedGraphAndPlanBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<hipdnn_flatbuffers_sdk::data_objects::SerializedGraphAndPlan>(SerializedGraphAndPlanIdentifier());
}

inline bool VerifySizePrefixedSerializedGraphAndPlanBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<hipdnn_flatbuffers_sdk::data_objects::SerializedGraphAndPlan>(SerializedGraphAndPlanIdentifier());
}

inline void FinishSerializedGraphAndPlanBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<hipdnn_flatbuffers_sdk::data_objects::SerializedGraphAndPlan> root) {
  fbb.Finish(root, SerializedGraphAndPlanIdentifier());
}

inline void FinishSizePrefixedSerializedGraphAndPlanBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<hipdnn_flatbuffers_sdk::data_objects::SerializedGraphAndPlan> root) {
  fbb.FinishSizePrefixed(root, SerializedGraphAndPlanIdentifier());
}

inline std::unique_ptr<hipdnn_flatbuffers_sdk::data_objects::SerializedGraphAndPlanT> UnPackSerializedGraphAndPlan(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<hipdnn_flatbuffers_sdk::data_objects::SerializedGraphAndPlanT>(GetSerializedGraphAndPlan(buf)->UnPack(res));
}

inline std::unique_ptr<hipdnn_flatbuffers_sdk::data_objects::SerializedGraphAndPlanT> UnPackSizePrefixedSerializedGraphAndPlan(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<hipdnn_flatbuffers_sdk::data_objects::SerializedGraphAndPlanT>(GetSizePrefixedSerializedGraphAndPlan(buf)->UnPack(res));
}

}  // namespace data_objects
}  // namespace hipdnn_flatbuffers_sdk

#endif  // FLATBUFFERS_GENERATED_SERIALIZEDGRAPHANDPLAN_HIPDNN_FLATBUFFERS_SDK_DATA_OBJECTS_H_
