flag_management:
  default_rules:
    carryforward: true # compare reports between projects or flags, not just the latest commit

comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false  # post comment even if coverage does not change
  require_base: no # post without previous or base report
  require_head: yes # must have PR or head report to post
  show_carryforward_flags: true # use carryforward for PRs

coverage:
  status:
    project:
      default:
        enabled: false # only check flags instead of whole monorepo
      composable_kernel:
        flags: [composable_kernel]
        target: 80%
      hipBLAS:
        flags: [hipBLAS]
        target: 80%
      hipBLASLt:
        flags: [hipBLASLt]
        target: 80%
      TensileLite:
        flags: [TensileLite]
        target: 80%
      hipCUB:
        flags: [hipCUB]
        target: 80%
      hipSPARSE:
        flags: [hipSPARSE]
        target: 80%
      hipSPARSELt:
        flags: [hipSPARSELt]
        target: 80%
      rocBLAS:
        flags: [rocBLAS]
        target: 80%
      rocRAND:
        flags: [rocRAND]
        target: 80%
      hipRAND:
        flags: [hipRAND]
        target: 80%
      hipDNN:
        flags: [hipDNN]
        target: 80%
      rocRoller:
        flags: [rocRoller]
        target: 80%
      rocSPARSE:
        flags: [rocSPARSE]
        target: 80%
      rocThrust:
        flags: [rocThrust]
        target: 80%
      hipFFT:
        flags: [hipFFT]
        target: 80%
      rocFFT:
        flags: [rocFFT]
        target: 80%
      Tensile:
        flags: [Tensile]
        target: 80%
      hipSOLVER:
        flags: [hipSOLVER]
        target: 80%
      rocSOLVER:
        flags: [rocSOLVER]
        target: 80%
