/* ************************************************************************
 * Copyright (C) 2025-2026 Advanced Micro Devices, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * ************************************************************************ */

/**
 * @file IROpcode.hpp
 * @brief Logical IR opcode enumeration
 *
 * Similar to GFX:: enum for assembly IR, this provides a unified opcode
 * system for logical IR instructions enabling fast pattern matching
 * via integer comparison instead of string comparison.
 */

#pragma once

#include <cstdint>
#include <string_view>

#include "stinkytofu/Export.hpp"

namespace stinkytofu {

/**
 * @brief Logical IR Instruction Opcodes
 *
 * Each logical IR instruction (VAddF32, VMulF32, etc.) has a unique
 * opcode for fast pattern matching and identification.
 *
 * Design notes:
 * - Similar to GFX:: enum for assembly IR
 * - Used by LogicalInstruction::getOpcode()
 * - Enables fast integer comparison in pattern matching
 * - Generated by tablegen from IRInstructionDefs.inc
 */
namespace logical {
enum Opcode : uint16_t {
    UNKNOWN = 0,

// Include generated opcode definitions
#include "LogicalOpcodes_generated.inc"

    // Special instruction opcodes (not auto-generated)
    MFMA,
    MXMFMA,
    SMFMA,
    Label,
    IntrinsicCall,
    SWaitAlu,
    SchedulingFence,

    NUM_OPCODES  // Sentinel value
};

/**
 * @brief Convert opcode to human-readable string
 * @param opcode The logical IR opcode
 * @return String representation (e.g., "VAddF32")
 */
STINKYTOFU_EXPORT const char* getOpcodeName(Opcode opcode);

/**
 * @brief Convert opcode to assembly mnemonic
 * @param opcode The logical IR opcode
 * @return Assembly mnemonic (e.g., "v_add_f32")
 */
STINKYTOFU_EXPORT const char* getOpcodeMnemonic(Opcode opcode);

/**
 * @brief Parse opcode from string
 * @param name Instruction name (CamelCase like "VMaxF32" or snake_case like "v_max_f32")
 * @return Corresponding logical IR opcode, or UNKNOWN if not found
 *
 * This function supports both naming conventions:
 * - CamelCase: "VAddF32", "VMaxF32", "VCmpGTF32"
 * - snake_case: "v_add_f32", "v_max_f32", "v_cmp_gt_f32"
 */
STINKYTOFU_EXPORT Opcode parseOpcode(const char* name);

}  // namespace logical

}  // namespace stinkytofu
