#!/bin/bash

# For the develop branch, bump hipblas version and rocblas/rocsolver dependency versions

OLD_HIPBLAS_VERSION="3.4.0"
NEW_HIPBLAS_VERSION="3.5.0"

OLD_MINIMUM_ROCBLAS_VERSION="5.4.0"
NEW_MINIMUM_ROCBLAS_VERSION="5.5.0"

OLD_MINIMUM_ROCSOLVER_VERSION="3.33.0"
NEW_MINIMUM_ROCSOLVER_VERSION="3.33.0"

OLD_MINIMUM_HIPBLAS_COMMON_VERSION="1.4.0"
NEW_MINIMUM_HIPBLAS_COMMON_VERSION="1.4.0"

OLD_SO_VERSION="hipblas_SOVERSION 3.4"
NEW_SO_VERSION="hipblas_SOVERSION 3.5"

sed -i "s/${OLD_HIPBLAS_VERSION}/${NEW_HIPBLAS_VERSION}/g" CMakeLists.txt
sed -i "s/${OLD_MINIMUM_ROCBLAS_VERSION}/${NEW_MINIMUM_ROCBLAS_VERSION}/g" CMakeLists.txt
sed -i "s/${OLD_MINIMUM_ROCSOLVER_VERSION}/${NEW_MINIMUM_ROCSOLVER_VERSION}/g" CMakeLists.txt
sed -i "s/${OLD_MINIMUM_HIPBLAS_COMMON_VERSION}/${NEW_MINIMUM_HIPBLAS_COMMON_VERSION}/g" CMakeLists.txt
sed -i "s/${OLD_SO_VERSION}/${NEW_SO_VERSION}/g" library/CMakeLists.txt
