# Characterization test — KernelWriter.py:884 branch `if kernel["HalfPLR"]:`
# Branch ID: aa1d28b3a0100f8f5ed22327c7a3d75e3d537e37
# Generated by parametric-chaos Run-3 (CodegenResidue surface); ADD-ONLY, never modify.
#
# Predicate: Python truthiness on kernel["HalfPLR"], a validated YAML int in {0,1,2,3}.
# Branch taken iff HalfPLR != 0.  Domain exhaustively enumerated; classification: fully-static.

import pytest

pytestmark = pytest.mark.unit


# ---------------------------------------------------------------------------
# Pure helper — mirrors the predicate at KernelWriter.py:884
# ---------------------------------------------------------------------------

def half_plr_enabled(half_plr: int) -> bool:
    """Mirror of branch at KernelWriter.py:884 -- `if kernel["HalfPLR"]`.

    HalfPLR is a validated YAML int in {0,1,2,3}; branch taken iff truthy (non-zero).
    pre:  0 <= half_plr <= 3
    post: __return__ == (half_plr != 0)
    """
    return bool(half_plr)


# ---------------------------------------------------------------------------
# True witnesses: HalfPLR in {1, 2, 3} -> branch taken
# ---------------------------------------------------------------------------

def test_half_plr_enabled_true_1():
    """HalfPLR=1 (bit0=A set) -> branch taken."""
    assert half_plr_enabled(1) is True


def test_half_plr_enabled_true_2():
    """HalfPLR=2 (bit1=B set) -> branch taken."""
    assert half_plr_enabled(2) is True


def test_half_plr_enabled_true_3():
    """HalfPLR=3 (both bits set) -> branch taken."""
    assert half_plr_enabled(3) is True


# ---------------------------------------------------------------------------
# False witness: HalfPLR=0 -> branch NOT taken
# ---------------------------------------------------------------------------

def test_half_plr_enabled_false_0():
    """HalfPLR=0 (default, disabled) -> branch NOT taken."""
    assert half_plr_enabled(0) is False


# ---------------------------------------------------------------------------
# Exhaustive enumeration over the full validated domain {0,1,2,3}
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("half_plr,expected", [
    (0, False),
    (1, True),
    (2, True),
    (3, True),
])
def test_half_plr_enabled_full_domain(half_plr, expected):
    """Exhaustive check: bool(half_plr) == (half_plr != 0) for all validated values."""
    assert half_plr_enabled(half_plr) is expected


# ---------------------------------------------------------------------------
# Predicate equivalence: half_plr_enabled(v) == (v != 0) for all domain values
# ---------------------------------------------------------------------------

def test_half_plr_predicate_equivalence():
    """half_plr_enabled mirrors the exact predicate `bool(kernel['HalfPLR'])`."""
    for v in range(4):
        assert half_plr_enabled(v) == (v != 0), f"mismatch at HalfPLR={v}"
