# Characterization test — KernelWriter.py:951 branch `elif scheduleIterAlg == 1:`
# Branch ID: 1c0151825aa4bb9615fe3d3ae10051f09c990486
# Generated by parametric-chaos Run-1 (CodegenResidue surface); ADD-ONLY, never modify.
#
# Predicate: scheduleIterAlg == 1
# The function-local `scheduleIterAlg` is seeded from self.states.scheduleIterAlg (line 877),
# then FORCED to 0 when (NLLlast and tailloopInNll) at lines 878-880.
# The elif at 951 fires iff the resulting effective value == 1.
# Domain: scheduleIterAlg in {0, 1, 2, 3} (kernel[\"_ScheduleIterAlg\"]; value 4 remapped to 0).
# Classification: solver-backed-under-assumptions (z3 4.16.0, in-container verified).

import pytest

pytestmark = pytest.mark.unit


# ---------------------------------------------------------------------------
# Pure helper — mirrors the predicate at KernelWriter.py:951
# ---------------------------------------------------------------------------

def schedule_iter_alg_is_one(schedule_iter_alg: int, nll_last: bool, tailloop_in_nll: bool) -> bool:
    """Pure model of KernelWriter.py:951 predicate `scheduleIterAlg == 1`.

    Mirrors lines 877-880: local scheduleIterAlg seeded from kernel["_ScheduleIterAlg"]
    (enum in {0,1,2,3}) but FORCED to 0 when (NLLlast and tailloopInNll). Branch fires iff ==1.

    pre:  0 <= schedule_iter_alg <= 3
    post: __return__ == ((0 if (nll_last and tailloop_in_nll) else schedule_iter_alg) == 1)
    """
    eff = 0 if (nll_last and tailloop_in_nll) else schedule_iter_alg
    return eff == 1


# ---------------------------------------------------------------------------
# True witness: scheduleIterAlg=1, no NLL override -> elif fires
# ---------------------------------------------------------------------------

def test_schedule_iter_alg_one_no_override():
    """scheduleIterAlg=1, NLLlast=False, tailloopInNll=False -> elif fires (schedule alg #1)."""
    assert schedule_iter_alg_is_one(1, False, False) is True


def test_schedule_iter_alg_one_nll_last_only():
    """scheduleIterAlg=1, NLLlast=True, tailloopInNll=False -> override not triggered -> elif fires."""
    assert schedule_iter_alg_is_one(1, True, False) is True


def test_schedule_iter_alg_one_tailloop_only():
    """scheduleIterAlg=1, NLLlast=False, tailloopInNll=True -> override not triggered -> elif fires."""
    assert schedule_iter_alg_is_one(1, False, True) is True


# ---------------------------------------------------------------------------
# False witnesses: scheduleIterAlg != 1, or NLL override fires
# ---------------------------------------------------------------------------

def test_schedule_iter_alg_zero_no_override():
    """scheduleIterAlg=0 -> handled by `if == 0` at line 882, elif skipped."""
    assert schedule_iter_alg_is_one(0, False, False) is False


def test_schedule_iter_alg_two_no_override():
    """scheduleIterAlg=2 -> falls through to elif at line 998, this elif skipped."""
    assert schedule_iter_alg_is_one(2, False, False) is False


def test_schedule_iter_alg_three_no_override():
    """scheduleIterAlg=3 -> falls through past this elif."""
    assert schedule_iter_alg_is_one(3, False, False) is False


def test_schedule_iter_alg_one_nll_override_fires():
    """scheduleIterAlg=1, NLLlast=True, tailloopInNll=True -> forced to 0 at line 880 -> elif skipped."""
    assert schedule_iter_alg_is_one(1, True, True) is False


# ---------------------------------------------------------------------------
# Exhaustive parametrize over full domain {0,1,2,3} x override states
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("sia,nll,til,expected", [
    # override NOT firing (nll and til not both True)
    (0, False, False, False),
    (1, False, False, True),   # canonical TRUE witness
    (2, False, False, False),
    (3, False, False, False),
    (0, True,  False, False),
    (1, True,  False, True),
    (2, True,  False, False),
    (3, True,  False, False),
    (0, False, True,  False),
    (1, False, True,  True),
    (2, False, True,  False),
    (3, False, True,  False),
    # override fires (nll=True AND til=True -> eff forced to 0)
    (0, True,  True,  False),
    (1, True,  True,  False),  # assumption-dependent FALSE: config=1 but overridden to 0
    (2, True,  True,  False),
    (3, True,  True,  False),
])
def test_schedule_iter_alg_full_domain(sia, nll, til, expected):
    """Full domain check: schedule_iter_alg_is_one matches predicate for all valid inputs."""
    assert schedule_iter_alg_is_one(sia, nll, til) is expected


# ---------------------------------------------------------------------------
# Predicate equivalence: helper mirrors the source exactly
# ---------------------------------------------------------------------------

def test_predicate_equivalence():
    """schedule_iter_alg_is_one mirrors `(0 if (nll and til) else sia) == 1` exactly."""
    for sia in range(4):
        for nll in (False, True):
            for til in (False, True):
                eff = 0 if (nll and til) else sia
                expected = (eff == 1)
                assert schedule_iter_alg_is_one(sia, nll, til) == expected, (
                    f"mismatch at sia={sia}, nll={nll}, til={til}"
                )
