#!/bin/bash -ex

# Copyright Advanced Micro Devices, Inc., or its affiliates.
# SPDX-License-Identifier: MIT

CODEQL_INSTALL_DIR=/opt/codeql
if [[ -n "$1" ]]; then
  CODEQL_INSTALL_DIR="$1"
fi

# Run install codeql script if zip not found
if [[ ! -f /opt/codeql/codeql-cli.zip ]]; then
  ./codeql/install_codeql "${CODEQL_INSTALL_DIR}"
fi

# Sets up a QLPack with dependencies for our check(s).
mkdir -p codeql/build
cd codeql/build
unzip -q ${CODEQL_INSTALL_DIR}/codeql-cli.zip
mv codeql-codeql-cli-* codeql-cli
