# Copyright © Advanced Micro Devices, Inc., or its affiliates.
# SPDX-License-Identifier: MIT

[tox]
envlist = py310, py311, py312, py313

[testenv]
deps =
    -r{toxinidir}/tox-requirements.txt
setenv =
    ROCM_PATH = {env:ROCM_PATH:/opt/rocm}
commands =
    pip install --upgrade pip
    pip install .
    pytest test/
allowlist_externals =
    sh
