################################################################################
# Copyright (C) 2026 Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: MIT
################################################################################
"""R5 — gfx942 complex GEMM / ComplexConjugate MAC path characterization.

Drives a SingleComplex (DataType=C, f32c) GEMM config with
ComplexConjugateB=True through the config-driven emit harness and asserts:
  1. Every emitted kernel is real gfx942 AMDGCN assembly (err==0).
  2. The emitted source contains the complex MAC negation markers emitted by
     KernelWriterAssembly.py lines 9285-9355 (ccVgprs / VAddF32 / four-MFMA
     complex multiply-add arms).

Target missing ranges in Tensile/KernelWriterAssembly.py:
  - 9285-9355 : ComplexConjugate MAC arms — ccVgprs allocation, VAddF32
                negation of Ar/Ai, four MFMA instructions for complex C += A*B.
                Gate: ``kernel["ProblemType"]["DataType"].isComplex()``
                (line 9282); conjugate arms additionally gate on
                ``ComplexConjugateA`` / ``ComplexConjugateB`` flags.

Note on DataType=Z (DoubleComplex): gfx942 lacks HasMFMA_f64, so Z kernels
are rejected at Solution derivation time (Solution.py line 1634). Only
SingleComplex (DataType=C) is CPU-emittable on gfx942.

Pure-assert test; no syrupy snapshot required.
"""

import os

import pytest

from config_harness import emit_kernels_from_config

pytestmark = pytest.mark.unit

_ARCH = "gfx942"

_CONFIG = os.path.join(
    os.path.dirname(__file__),
    "data",
    "test_data",
    "_designed",
    "gfx942",
    "complex_cc.yaml",
)


def test_r5_complex_cc_emits_assembly():
    """Complex GEMM (NC, ComplexConjugateB=True) emits real gfx942 assembly."""
    results = emit_kernels_from_config(_CONFIG, limit=8, arch=_ARCH)
    assert len(results) >= 1, f"Expected >=1 kernel, got {len(results)}"
    assert all(err == 0 for (_b, _s, err) in results), (
        "All kernels must emit with err==0; "
        + str([(b, e) for (b, _s, e) in results if e != 0])
    )
    for base, src, _err in results:
        assert src and len(src.splitlines()) > 100, f"Kernel {base!r} source too short"
        assert ".amdgcn_target" in src, f"Kernel {base!r} missing .amdgcn_target"
        assert "gfx942" in src, f"Kernel {base!r} missing gfx942 arch marker"
        assert base.startswith("Cijk_"), f"Unexpected basename: {base!r}"


def test_r5_complex_cc_conjugate_negation_present():
    """Complex GEMM emits VAddF32 negation (Ai=-Ai or Ar=-Ar) for conjugate MAC arms.

    KernelWriterAssembly.py 9285-9355 emits negation instructions as comments
    in the assembly source when ComplexConjugateA or ComplexConjugateB is True.
    The comment strings 'Ai=-Ai' and 'Ar=-Ar' are the canonical markers
    generated by VAddX(... comment='Ai=-Ai') / VAddX(... comment='Ar=-Ar')
    at lines 9318, 9325, 9332.
    """
    results = emit_kernels_from_config(_CONFIG, limit=8, arch=_ARCH)
    assert len(results) >= 1, "Need at least one kernel to check"
    found_negation = False
    for base, src, err in results:
        if err != 0 or not src:
            continue
        # With ComplexConjugateB=True and ComplexConjugateA=False:
        #   ccVgprs[2] is allocated (ccB arm, line 9327-9333).
        #   VAddF32 emits with comment "Ar=-Ar" (line 9332).
        # The complex MAC Cr/Ci update comments (lines 9341, 9345, 9349, 9353)
        # contain 'Cr +=' and 'Ci +=' strings.
        if "Ar=-Ar" in src or "Ai=-Ai" in src:
            found_negation = True
        # Also verify the four-MFMA complex multiply-add pattern is present.
        assert "Cr +=" in src, f"Kernel {base!r}: missing 'Cr +=' complex MAC comment"
        assert "Ci +=" in src, f"Kernel {base!r}: missing 'Ci +=' complex MAC comment"
    assert found_negation, (
        "Expected at least one kernel to contain 'Ar=-Ar' or 'Ai=-Ai' "
        "(ComplexConjugate negation, KWA 9318/9325/9332) — check config has "
        "ComplexConjugateA=True or ComplexConjugateB=True"
    )
