#!/bin/bash

# for the develop branch this script bumps the Tensile version and hash and the rocBLAS version

OLD_TENSILE_VERSION="TENSILE_VERSION 4.47.0"
NEW_TENSILE_VERSION="TENSILE_VERSION 4.48.0"

OLD_ROCBLAS_VERSION="5.4.0"
NEW_ROCBLAS_VERSION="5.5.0"

OLD_SO_VERSION="rocblas_SOVERSION 5.4"
NEW_SO_VERSION="rocblas_SOVERSION 5.5"

OLD_HIPBLASLT_VERSION="HIPBLASLT_VERSION 1.2.2"
NEW_HIPBLASLT_VERSION="HIPBLASLT_VERSION 1.2.3"

sed -i "s/${OLD_TENSILE_VERSION}/${NEW_TENSILE_VERSION}/g" CMakeLists.txt

sed -i "s/${OLD_ROCBLAS_VERSION}/${NEW_ROCBLAS_VERSION}/g" CMakeLists.txt

sed -i "s/${OLD_SO_VERSION}/${NEW_SO_VERSION}/g" library/CMakeLists.txt

sed -i "s/${OLD_HIPBLASLT_VERSION}/${NEW_HIPBLASLT_VERSION}/g" CMakeLists.txt
