################################################################################
#
# Copyright (C) 2025-2026 Advanced Micro Devices, Inc. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell cop-
# ies of the Software, and to permit persons to whom the Software is furnished
# to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IM-
# PLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNE-
# CTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
################################################################################
"""Shim for ``rocisa.instruction``.

What this file is:
    Mirrors ``rocisa/rocisa/src/instruction/`` (``init_inst`` plus the
    per-category files: ``branch.cpp``, ``cmp.cpp``, ``common.cpp``,
    ``cvt.cpp``, ``mem.cpp``, ``mfma.cpp``, ``instruction.cpp``,
    ``extension.cpp``).

What it does (real):
    - None.

Not yet done (dummy):
    - All instruction classes (``Buffer*``, ``DS*``, ``Flat*``,
      ``S*``, ``V*``, ``MFMA*`` / ``SMFMA*``, ...).
    - ``getMFMAIssueLatency`` / ``getSMFMAIssueLatency`` — currently
      return ``None``; Tensile's ``_initKernel`` unpacks them as
      ``(int, int)``, so they must return a 2-tuple soon.
    - Extension functions: ``SLongBranch*``, ``SCLongBranch*``,
      ``SGetPositivePCOffset``, ``SMulInt64to32``, ``VCvtBF16toFP32``.

logicalIR correspondence (strict name match):
    A class carries a ``# logicalIR: <OpName>`` comment iff
    ``shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc``
    contains an entry with exactly the same name. No approximate
    "same family" matches.
"""

from __future__ import annotations

from ._dummy import make_dummy_class, make_dummy_func

_P = "rocisa.instruction"



# ==========================================================================
# Base instruction types
# source: rocisa/rocisa/src/instruction/instruction.cpp
# ==========================================================================
Instruction = make_dummy_class(f"{_P}.Instruction")
CompositeInstruction = make_dummy_class(f"{_P}.CompositeInstruction")
CommonInstruction = make_dummy_class(f"{_P}.CommonInstruction")
MacroInstruction = make_dummy_class(f"{_P}.MacroInstruction")


# ==========================================================================
# Branch instructions
# source: rocisa/rocisa/src/instruction/branch.cpp
# ==========================================================================
BranchInstruction = make_dummy_class(f"{_P}.BranchInstruction")
SBranch = make_dummy_class(f"{_P}.SBranch")
SCBranchSCC0 = make_dummy_class(f"{_P}.SCBranchSCC0")
SCBranchSCC1 = make_dummy_class(f"{_P}.SCBranchSCC1")
SAddPCI64_SIMM = make_dummy_class(f"{_P}.SAddPCI64_SIMM")
SCBranchVCCNZ = make_dummy_class(f"{_P}.SCBranchVCCNZ")
SCBranchVCCZ = make_dummy_class(f"{_P}.SCBranchVCCZ")
SSetPCB64 = make_dummy_class(f"{_P}.SSetPCB64")
SSwapPCB64 = make_dummy_class(f"{_P}.SSwapPCB64")
SCBranchExecZ = make_dummy_class(f"{_P}.SCBranchExecZ")
SCBranchExecNZ = make_dummy_class(f"{_P}.SCBranchExecNZ")


# ==========================================================================
# Compare instructions
# source: rocisa/rocisa/src/instruction/cmp.cpp
# ==========================================================================
VCmpInstruction = make_dummy_class(f"{_P}.VCmpInstruction")
VCmpXInstruction = make_dummy_class(f"{_P}.VCmpXInstruction")
# logicalIR: SCmpEQI32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SCmpEQI32 = make_dummy_class(f"{_P}.SCmpEQI32")
# logicalIR: SCmpEQU32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SCmpEQU32 = make_dummy_class(f"{_P}.SCmpEQU32")
# logicalIR: SCmpEQU64  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SCmpEQU64 = make_dummy_class(f"{_P}.SCmpEQU64")
# logicalIR: SCmpGeI32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SCmpGeI32 = make_dummy_class(f"{_P}.SCmpGeI32")
# logicalIR: SCmpGeU32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SCmpGeU32 = make_dummy_class(f"{_P}.SCmpGeU32")
# logicalIR: SCmpGtI32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SCmpGtI32 = make_dummy_class(f"{_P}.SCmpGtI32")
# logicalIR: SCmpGtU32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SCmpGtU32 = make_dummy_class(f"{_P}.SCmpGtU32")
# logicalIR: SCmpLeI32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SCmpLeI32 = make_dummy_class(f"{_P}.SCmpLeI32")
# logicalIR: SCmpLeU32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SCmpLeU32 = make_dummy_class(f"{_P}.SCmpLeU32")
# logicalIR: SCmpLgU32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SCmpLgU32 = make_dummy_class(f"{_P}.SCmpLgU32")
# logicalIR: SCmpLgI32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SCmpLgI32 = make_dummy_class(f"{_P}.SCmpLgI32")
# logicalIR: SCmpLgU64  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SCmpLgU64 = make_dummy_class(f"{_P}.SCmpLgU64")
# logicalIR: SCmpLtI32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SCmpLtI32 = make_dummy_class(f"{_P}.SCmpLtI32")
# logicalIR: SCmpLtU32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SCmpLtU32 = make_dummy_class(f"{_P}.SCmpLtU32")
# logicalIR: SBitcmp1B32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SBitcmp1B32 = make_dummy_class(f"{_P}.SBitcmp1B32")
SCmpKEQU32 = make_dummy_class(f"{_P}.SCmpKEQU32")
SCmpKGeU32 = make_dummy_class(f"{_P}.SCmpKGeU32")
SCmpKGtU32 = make_dummy_class(f"{_P}.SCmpKGtU32")
SCmpKLGU32 = make_dummy_class(f"{_P}.SCmpKLGU32")
# logicalIR: VCmpEQF32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCmpEQF32 = make_dummy_class(f"{_P}.VCmpEQF32")
# logicalIR: VCmpEQF64  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCmpEQF64 = make_dummy_class(f"{_P}.VCmpEQF64")
# logicalIR: VCmpEQU32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCmpEQU32 = make_dummy_class(f"{_P}.VCmpEQU32")
# logicalIR: VCmpEQI32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCmpEQI32 = make_dummy_class(f"{_P}.VCmpEQI32")
# logicalIR: VCmpGEF16  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCmpGEF16 = make_dummy_class(f"{_P}.VCmpGEF16")
# logicalIR: VCmpGTF16  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCmpGTF16 = make_dummy_class(f"{_P}.VCmpGTF16")
# logicalIR: VCmpGEF32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCmpGEF32 = make_dummy_class(f"{_P}.VCmpGEF32")
# logicalIR: VCmpGTF32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCmpGTF32 = make_dummy_class(f"{_P}.VCmpGTF32")
# logicalIR: VCmpGEF64  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCmpGEF64 = make_dummy_class(f"{_P}.VCmpGEF64")
# logicalIR: VCmpGTF64  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCmpGTF64 = make_dummy_class(f"{_P}.VCmpGTF64")
# logicalIR: VCmpGEI32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCmpGEI32 = make_dummy_class(f"{_P}.VCmpGEI32")
# logicalIR: VCmpGTI32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCmpGTI32 = make_dummy_class(f"{_P}.VCmpGTI32")
# logicalIR: VCmpGEU32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCmpGEU32 = make_dummy_class(f"{_P}.VCmpGEU32")
# logicalIR: VCmpGtU32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCmpGtU32 = make_dummy_class(f"{_P}.VCmpGtU32")
# logicalIR: VCmpLeU32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCmpLeU32 = make_dummy_class(f"{_P}.VCmpLeU32")
# logicalIR: VCmpLeI32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCmpLeI32 = make_dummy_class(f"{_P}.VCmpLeI32")
# logicalIR: VCmpLtI32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCmpLtI32 = make_dummy_class(f"{_P}.VCmpLtI32")
# logicalIR: VCmpLtU32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCmpLtU32 = make_dummy_class(f"{_P}.VCmpLtU32")
# logicalIR: VCmpUF32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCmpUF32 = make_dummy_class(f"{_P}.VCmpUF32")
# logicalIR: VCmpNeI32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCmpNeI32 = make_dummy_class(f"{_P}.VCmpNeI32")
# logicalIR: VCmpNeU32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCmpNeU32 = make_dummy_class(f"{_P}.VCmpNeU32")
# logicalIR: VCmpNeU64  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCmpNeU64 = make_dummy_class(f"{_P}.VCmpNeU64")
# logicalIR: VCmpClassF32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCmpClassF32 = make_dummy_class(f"{_P}.VCmpClassF32")
# logicalIR: VCmpXClassF32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCmpXClassF32 = make_dummy_class(f"{_P}.VCmpXClassF32")
# logicalIR: VCmpXEqU32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCmpXEqU32 = make_dummy_class(f"{_P}.VCmpXEqU32")
# logicalIR: VCmpXGeU32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCmpXGeU32 = make_dummy_class(f"{_P}.VCmpXGeU32")
# logicalIR: VCmpXGtU32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCmpXGtU32 = make_dummy_class(f"{_P}.VCmpXGtU32")
# logicalIR: VCmpXLeU32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCmpXLeU32 = make_dummy_class(f"{_P}.VCmpXLeU32")
# logicalIR: VCmpXLeI32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCmpXLeI32 = make_dummy_class(f"{_P}.VCmpXLeI32")
# logicalIR: VCmpXLtF32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCmpXLtF32 = make_dummy_class(f"{_P}.VCmpXLtF32")
# logicalIR: VCmpXLtI32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCmpXLtI32 = make_dummy_class(f"{_P}.VCmpXLtI32")
# logicalIR: VCmpXLtU32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCmpXLtU32 = make_dummy_class(f"{_P}.VCmpXLtU32")
# logicalIR: VCmpXLtU64  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCmpXLtU64 = make_dummy_class(f"{_P}.VCmpXLtU64")
# logicalIR: VCmpXNeU16  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCmpXNeU16 = make_dummy_class(f"{_P}.VCmpXNeU16")
# logicalIR: VCmpXNeU32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCmpXNeU32 = make_dummy_class(f"{_P}.VCmpXNeU32")


# ==========================================================================
# Common ALU / control instructions
# source: rocisa/rocisa/src/instruction/common.cpp
# ==========================================================================
# logicalIR: SAbsI32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SAbsI32 = make_dummy_class(f"{_P}.SAbsI32")
# logicalIR: SMaxI32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SMaxI32 = make_dummy_class(f"{_P}.SMaxI32")
# logicalIR: SMaxU32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SMaxU32 = make_dummy_class(f"{_P}.SMaxU32")
# logicalIR: SMinI32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SMinI32 = make_dummy_class(f"{_P}.SMinI32")
# logicalIR: SMinU32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SMinU32 = make_dummy_class(f"{_P}.SMinU32")
# logicalIR: SAddI32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SAddI32 = make_dummy_class(f"{_P}.SAddI32")
# logicalIR: SAddU32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SAddU32 = make_dummy_class(f"{_P}.SAddU32")
# logicalIR: SAddCU32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SAddCU32 = make_dummy_class(f"{_P}.SAddCU32")
# logicalIR: SMulI32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SMulI32 = make_dummy_class(f"{_P}.SMulI32")
# logicalIR: SMulHII32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SMulHII32 = make_dummy_class(f"{_P}.SMulHII32")
# logicalIR: SMulHIU32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SMulHIU32 = make_dummy_class(f"{_P}.SMulHIU32")
# logicalIR: SMulLOU32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SMulLOU32 = make_dummy_class(f"{_P}.SMulLOU32")
# logicalIR: SSubI32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SSubI32 = make_dummy_class(f"{_P}.SSubI32")
# logicalIR: SSubU32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SSubU32 = make_dummy_class(f"{_P}.SSubU32")
# logicalIR: SSubBU32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SSubBU32 = make_dummy_class(f"{_P}.SSubBU32")
# logicalIR: SCSelectB32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SCSelectB32 = make_dummy_class(f"{_P}.SCSelectB32")
SCSelectB64 = make_dummy_class(f"{_P}.SCSelectB64")
# logicalIR: SAndB32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SAndB32 = make_dummy_class(f"{_P}.SAndB32")
# logicalIR: SAndB64  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SAndB64 = make_dummy_class(f"{_P}.SAndB64")
# logicalIR: SAndN2B32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SAndN2B32 = make_dummy_class(f"{_P}.SAndN2B32")
# logicalIR: SOrB32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SOrB32 = make_dummy_class(f"{_P}.SOrB32")
# logicalIR: SXorB32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SXorB32 = make_dummy_class(f"{_P}.SXorB32")
# logicalIR: SOrB64  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SOrB64 = make_dummy_class(f"{_P}.SOrB64")
# logicalIR: SSubU64  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SSubU64 = make_dummy_class(f"{_P}.SSubU64")
# logicalIR: SGetPCB64  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SGetPCB64 = make_dummy_class(f"{_P}.SGetPCB64")
# logicalIR: SLShiftLeftB32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SLShiftLeftB32 = make_dummy_class(f"{_P}.SLShiftLeftB32")
# logicalIR: SLShiftRightB32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SLShiftRightB32 = make_dummy_class(f"{_P}.SLShiftRightB32")
# logicalIR: SLShiftLeftB64  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SLShiftLeftB64 = make_dummy_class(f"{_P}.SLShiftLeftB64")
# logicalIR: SLShiftRightB64  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SLShiftRightB64 = make_dummy_class(f"{_P}.SLShiftRightB64")
# logicalIR: SAShiftRightI32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SAShiftRightI32 = make_dummy_class(f"{_P}.SAShiftRightI32")
# logicalIR: SLShiftLeft1AddU32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SLShiftLeft1AddU32 = make_dummy_class(f"{_P}.SLShiftLeft1AddU32")
# logicalIR: SLShiftLeft2AddU32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SLShiftLeft2AddU32 = make_dummy_class(f"{_P}.SLShiftLeft2AddU32")
# logicalIR: SLShiftLeft3AddU32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SLShiftLeft3AddU32 = make_dummy_class(f"{_P}.SLShiftLeft3AddU32")
# logicalIR: SLShiftLeft4AddU32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SLShiftLeft4AddU32 = make_dummy_class(f"{_P}.SLShiftLeft4AddU32")
# logicalIR: SSetMask  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SSetMask = make_dummy_class(f"{_P}.SSetMask")
# logicalIR: SMovB32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SMovB32 = make_dummy_class(f"{_P}.SMovB32")
# logicalIR: SMovB64  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SMovB64 = make_dummy_class(f"{_P}.SMovB64")
# logicalIR: SCMovB32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SCMovB32 = make_dummy_class(f"{_P}.SCMovB32")
# logicalIR: SCMovB64  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SCMovB64 = make_dummy_class(f"{_P}.SCMovB64")
# logicalIR: SFf1B32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SFf1B32 = make_dummy_class(f"{_P}.SFf1B32")
# logicalIR: SBfmB32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SBfmB32 = make_dummy_class(f"{_P}.SBfmB32")
SFlbitI32B32 = make_dummy_class(f"{_P}.SFlbitI32B32")
# logicalIR: SMovkI32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SMovkI32 = make_dummy_class(f"{_P}.SMovkI32")
# logicalIR: SSExtI16toI32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SSExtI16toI32 = make_dummy_class(f"{_P}.SSExtI16toI32")
# logicalIR: SAndSaveExecB32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SAndSaveExecB32 = make_dummy_class(f"{_P}.SAndSaveExecB32")
# logicalIR: SAndSaveExecB64  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SAndSaveExecB64 = make_dummy_class(f"{_P}.SAndSaveExecB64")
# logicalIR: SOrSaveExecB32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SOrSaveExecB32 = make_dummy_class(f"{_P}.SOrSaveExecB32")
# logicalIR: SOrSaveExecB64  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SOrSaveExecB64 = make_dummy_class(f"{_P}.SOrSaveExecB64")
SSetPrior = make_dummy_class(f"{_P}.SSetPrior")
# logicalIR: SBarrier  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SBarrier = make_dummy_class(f"{_P}.SBarrier")
SDcacheWb = make_dummy_class(f"{_P}.SDcacheWb")
SNop = make_dummy_class(f"{_P}.SNop")
VNop = make_dummy_class(f"{_P}.VNop")
SEndpgm = make_dummy_class(f"{_P}.SEndpgm")
SSleep = make_dummy_class(f"{_P}.SSleep")
SSetVgprMsb = make_dummy_class(f"{_P}.SSetVgprMsb")
# logicalIR: SGetRegB32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SGetRegB32 = make_dummy_class(f"{_P}.SGetRegB32")
# logicalIR: SSetRegB32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SSetRegB32 = make_dummy_class(f"{_P}.SSetRegB32")
# logicalIR: SSetRegIMM32B32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
SSetRegIMM32B32 = make_dummy_class(f"{_P}.SSetRegIMM32B32")
_SWaitCnt = make_dummy_class(f"{_P}._SWaitCnt")
_SWaitCntVscnt = make_dummy_class(f"{_P}._SWaitCntVscnt")
_SWaitStorecnt = make_dummy_class(f"{_P}._SWaitStorecnt")
_SWaitLoadcnt = make_dummy_class(f"{_P}._SWaitLoadcnt")
_SWaitKMcnt = make_dummy_class(f"{_P}._SWaitKMcnt")
_SWaitDscnt = make_dummy_class(f"{_P}._SWaitDscnt")
SWaitCnt = make_dummy_class(f"{_P}.SWaitCnt")
SWaitTensorcnt = make_dummy_class(f"{_P}.SWaitTensorcnt")
SWaitAlu = make_dummy_class(f"{_P}.SWaitAlu")
SDelayAlu = make_dummy_class(f"{_P}.SDelayAlu")
# logicalIR: VAddF16  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VAddF16 = make_dummy_class(f"{_P}.VAddF16")
# logicalIR: VAddF32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VAddF32 = make_dummy_class(f"{_P}.VAddF32")
# logicalIR: VAddF64  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VAddF64 = make_dummy_class(f"{_P}.VAddF64")
# logicalIR: VAddI32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VAddI32 = make_dummy_class(f"{_P}.VAddI32")
# logicalIR: VAddU32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VAddU32 = make_dummy_class(f"{_P}.VAddU32")
# logicalIR: VAddCOU32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VAddCOU32 = make_dummy_class(f"{_P}.VAddCOU32")
# logicalIR: VAddCCOU32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VAddCCOU32 = make_dummy_class(f"{_P}.VAddCCOU32")
# logicalIR: VAddPKF16  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VAddPKF16 = make_dummy_class(f"{_P}.VAddPKF16")
_VAddPKF32 = make_dummy_class(f"{_P}._VAddPKF32")
# logicalIR: VAddPKF32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VAddPKF32 = make_dummy_class(f"{_P}.VAddPKF32")
# logicalIR: VAdd3U32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VAdd3U32 = make_dummy_class(f"{_P}.VAdd3U32")
# logicalIR: VMulF16  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VMulF16 = make_dummy_class(f"{_P}.VMulF16")
# logicalIR: VMulF32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VMulF32 = make_dummy_class(f"{_P}.VMulF32")
# logicalIR: VMulF64  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VMulF64 = make_dummy_class(f"{_P}.VMulF64")
# logicalIR: VMulPKF16  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VMulPKF16 = make_dummy_class(f"{_P}.VMulPKF16")
# logicalIR: VMulPKF32S  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VMulPKF32S = make_dummy_class(f"{_P}.VMulPKF32S")
_VMulPKF32 = make_dummy_class(f"{_P}._VMulPKF32")
# logicalIR: VMulPKF32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VMulPKF32 = make_dummy_class(f"{_P}.VMulPKF32")
# logicalIR: VMulLOU32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VMulLOU32 = make_dummy_class(f"{_P}.VMulLOU32")
# logicalIR: VMulHII32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VMulHII32 = make_dummy_class(f"{_P}.VMulHII32")
# logicalIR: VMulHIU32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VMulHIU32 = make_dummy_class(f"{_P}.VMulHIU32")
# logicalIR: VMulI32I24  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VMulI32I24 = make_dummy_class(f"{_P}.VMulI32I24")
# logicalIR: VMulU32U24  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VMulU32U24 = make_dummy_class(f"{_P}.VMulU32U24")
# logicalIR: VSubF32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VSubF32 = make_dummy_class(f"{_P}.VSubF32")
# logicalIR: VSubI32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VSubI32 = make_dummy_class(f"{_P}.VSubI32")
# logicalIR: VSubU32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VSubU32 = make_dummy_class(f"{_P}.VSubU32")
# logicalIR: VSubCoU32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VSubCoU32 = make_dummy_class(f"{_P}.VSubCoU32")
# logicalIR: VMacF32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VMacF32 = make_dummy_class(f"{_P}.VMacF32")
# logicalIR: VDot2CF32F16  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VDot2CF32F16 = make_dummy_class(f"{_P}.VDot2CF32F16")
# logicalIR: VDot2CF32BF16  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VDot2CF32BF16 = make_dummy_class(f"{_P}.VDot2CF32BF16")
# logicalIR: VDot2F32F16  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VDot2F32F16 = make_dummy_class(f"{_P}.VDot2F32F16")
# logicalIR: VDot2F32BF16  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VDot2F32BF16 = make_dummy_class(f"{_P}.VDot2F32BF16")
# logicalIR: VFmaF16  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VFmaF16 = make_dummy_class(f"{_P}.VFmaF16")
# logicalIR: VFmaF32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VFmaF32 = make_dummy_class(f"{_P}.VFmaF32")
# logicalIR: VFmaF64  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VFmaF64 = make_dummy_class(f"{_P}.VFmaF64")
# logicalIR: VFmaPKF16  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VFmaPKF16 = make_dummy_class(f"{_P}.VFmaPKF16")
# logicalIR: VFmaMixF32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VFmaMixF32 = make_dummy_class(f"{_P}.VFmaMixF32")
# logicalIR: VMadI32I24  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VMadI32I24 = make_dummy_class(f"{_P}.VMadI32I24")
# logicalIR: VMadU32U24  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VMadU32U24 = make_dummy_class(f"{_P}.VMadU32U24")
# logicalIR: VMadMixF32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VMadMixF32 = make_dummy_class(f"{_P}.VMadMixF32")
# logicalIR: VExpF16  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VExpF16 = make_dummy_class(f"{_P}.VExpF16")
# logicalIR: VExpF32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VExpF32 = make_dummy_class(f"{_P}.VExpF32")
# logicalIR: VRcpF16  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VRcpF16 = make_dummy_class(f"{_P}.VRcpF16")
# logicalIR: VRcpF32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VRcpF32 = make_dummy_class(f"{_P}.VRcpF32")
# logicalIR: VRcpIFlagF32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VRcpIFlagF32 = make_dummy_class(f"{_P}.VRcpIFlagF32")
VRcpF64 = make_dummy_class(f"{_P}.VRcpF64")
# logicalIR: VRsqF16  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VRsqF16 = make_dummy_class(f"{_P}.VRsqF16")
# logicalIR: VRsqF32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VRsqF32 = make_dummy_class(f"{_P}.VRsqF32")
# logicalIR: VRsqIFlagF32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VRsqIFlagF32 = make_dummy_class(f"{_P}.VRsqIFlagF32")
# logicalIR: VMaxF16  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VMaxF16 = make_dummy_class(f"{_P}.VMaxF16")
# logicalIR: VMaxF32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VMaxF32 = make_dummy_class(f"{_P}.VMaxF32")
# logicalIR: VMaxF64  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VMaxF64 = make_dummy_class(f"{_P}.VMaxF64")
# logicalIR: VMaxI32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VMaxI32 = make_dummy_class(f"{_P}.VMaxI32")
# logicalIR: VMaxPKF16  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VMaxPKF16 = make_dummy_class(f"{_P}.VMaxPKF16")
# logicalIR: VMed3I32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VMed3I32 = make_dummy_class(f"{_P}.VMed3I32")
# logicalIR: VMed3F32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VMed3F32 = make_dummy_class(f"{_P}.VMed3F32")
# logicalIR: VMinF16  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VMinF16 = make_dummy_class(f"{_P}.VMinF16")
# logicalIR: VMinF32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VMinF32 = make_dummy_class(f"{_P}.VMinF32")
# logicalIR: VMinF64  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VMinF64 = make_dummy_class(f"{_P}.VMinF64")
# logicalIR: VMinI32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VMinI32 = make_dummy_class(f"{_P}.VMinI32")
# logicalIR: VAndB32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VAndB32 = make_dummy_class(f"{_P}.VAndB32")
# logicalIR: VAndOrB32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VAndOrB32 = make_dummy_class(f"{_P}.VAndOrB32")
# logicalIR: VNotB32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VNotB32 = make_dummy_class(f"{_P}.VNotB32")
# logicalIR: VOrB32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VOrB32 = make_dummy_class(f"{_P}.VOrB32")
# logicalIR: VXorB32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VXorB32 = make_dummy_class(f"{_P}.VXorB32")
# logicalIR: VPrngB32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VPrngB32 = make_dummy_class(f"{_P}.VPrngB32")
# logicalIR: VCndMaskB32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCndMaskB32 = make_dummy_class(f"{_P}.VCndMaskB32")
# logicalIR: VLShiftLeftB16  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VLShiftLeftB16 = make_dummy_class(f"{_P}.VLShiftLeftB16")
# logicalIR: VLShiftLeftB32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VLShiftLeftB32 = make_dummy_class(f"{_P}.VLShiftLeftB32")
# logicalIR: VLShiftRightB32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VLShiftRightB32 = make_dummy_class(f"{_P}.VLShiftRightB32")
# logicalIR: VLShiftLeftB64  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VLShiftLeftB64 = make_dummy_class(f"{_P}.VLShiftLeftB64")
# logicalIR: VLShiftRightB64  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VLShiftRightB64 = make_dummy_class(f"{_P}.VLShiftRightB64")
_VLShiftLeftOrB32 = make_dummy_class(f"{_P}._VLShiftLeftOrB32")
# logicalIR: VAShiftRightI32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VAShiftRightI32 = make_dummy_class(f"{_P}.VAShiftRightI32")
# logicalIR: VLShiftLeftOrB32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VLShiftLeftOrB32 = make_dummy_class(f"{_P}.VLShiftLeftOrB32")
_VAddLShiftLeftU32 = make_dummy_class(f"{_P}._VAddLShiftLeftU32")
VAddLShiftLeftU32 = make_dummy_class(f"{_P}.VAddLShiftLeftU32")
_VLShiftLeftAddU32 = make_dummy_class(f"{_P}._VLShiftLeftAddU32")
VLShiftLeftAddU32 = make_dummy_class(f"{_P}.VLShiftLeftAddU32")
# logicalIR: VMovB32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VMovB32 = make_dummy_class(f"{_P}.VMovB32")
_VMovB64 = make_dummy_class(f"{_P}._VMovB64")
# logicalIR: VMovB64  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VMovB64 = make_dummy_class(f"{_P}.VMovB64")
# logicalIR: VSwapB32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VSwapB32 = make_dummy_class(f"{_P}.VSwapB32")
# logicalIR: VBfeI32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VBfeI32 = make_dummy_class(f"{_P}.VBfeI32")
# logicalIR: VBfeU32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VBfeU32 = make_dummy_class(f"{_P}.VBfeU32")
# logicalIR: VBfiB32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VBfiB32 = make_dummy_class(f"{_P}.VBfiB32")
# logicalIR: VPackF16toB32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VPackF16toB32 = make_dummy_class(f"{_P}.VPackF16toB32")
# logicalIR: VAccvgprReadB32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VAccvgprReadB32 = make_dummy_class(f"{_P}.VAccvgprReadB32")
# logicalIR: VAccvgprWrite  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VAccvgprWrite = make_dummy_class(f"{_P}.VAccvgprWrite")
# logicalIR: VAccvgprWriteB32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VAccvgprWriteB32 = make_dummy_class(f"{_P}.VAccvgprWriteB32")
# logicalIR: VReadfirstlaneB32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VReadfirstlaneB32 = make_dummy_class(f"{_P}.VReadfirstlaneB32")
VReadlaneB32 = make_dummy_class(f"{_P}.VReadlaneB32")
VWritelaneB32 = make_dummy_class(f"{_P}.VWritelaneB32")
# logicalIR: VRndneF32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VRndneF32 = make_dummy_class(f"{_P}.VRndneF32")
# logicalIR: VPermB32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VPermB32 = make_dummy_class(f"{_P}.VPermB32")


# ==========================================================================
# Conversion instructions
# source: rocisa/rocisa/src/instruction/cvt.cpp
# ==========================================================================
VCvtInstruction = make_dummy_class(f"{_P}.VCvtInstruction")
# logicalIR: VCvtF16toF32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCvtF16toF32 = make_dummy_class(f"{_P}.VCvtF16toF32")
# logicalIR: VCvtF32toF16  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCvtF32toF16 = make_dummy_class(f"{_P}.VCvtF32toF16")
VCvtPkF32toF16 = make_dummy_class(f"{_P}.VCvtPkF32toF16")
# logicalIR: VCvtF32toU32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCvtF32toU32 = make_dummy_class(f"{_P}.VCvtF32toU32")
# logicalIR: VCvtU32toF32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCvtU32toF32 = make_dummy_class(f"{_P}.VCvtU32toF32")
VCvtF64toU32 = make_dummy_class(f"{_P}.VCvtF64toU32")
VCvtU32toF64 = make_dummy_class(f"{_P}.VCvtU32toF64")
# logicalIR: VCvtI32toF32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCvtI32toF32 = make_dummy_class(f"{_P}.VCvtI32toF32")
# logicalIR: VCvtF32toI32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCvtF32toI32 = make_dummy_class(f"{_P}.VCvtF32toI32")
# logicalIR: VCvtFP8toF32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCvtFP8toF32 = make_dummy_class(f"{_P}.VCvtFP8toF32")
# logicalIR: VCvtBF8toF32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCvtBF8toF32 = make_dummy_class(f"{_P}.VCvtBF8toF32")
# logicalIR: VCvtPkFP8toF32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCvtPkFP8toF32 = make_dummy_class(f"{_P}.VCvtPkFP8toF32")
# logicalIR: VCvtPkBF8toF32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCvtPkBF8toF32 = make_dummy_class(f"{_P}.VCvtPkBF8toF32")
# logicalIR: VCvtPkF32toBF8  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCvtPkF32toBF8 = make_dummy_class(f"{_P}.VCvtPkF32toBF8")
# logicalIR: VCvtSRF32toFP8  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCvtSRF32toFP8 = make_dummy_class(f"{_P}.VCvtSRF32toFP8")
# logicalIR: VCvtSRF32toBF8  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCvtSRF32toBF8 = make_dummy_class(f"{_P}.VCvtSRF32toBF8")
# logicalIR: VCvtScalePkFP8toF16  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCvtScalePkFP8toF16 = make_dummy_class(f"{_P}.VCvtScalePkFP8toF16")
# logicalIR: VCvtScalePkBF8toF16  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCvtScalePkBF8toF16 = make_dummy_class(f"{_P}.VCvtScalePkBF8toF16")
# logicalIR: VCvtScaleFP8toF16  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCvtScaleFP8toF16 = make_dummy_class(f"{_P}.VCvtScaleFP8toF16")
VCvtFP8toF16 = make_dummy_class(f"{_P}.VCvtFP8toF16")
# logicalIR: VCvtScalePkF16toFP8  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCvtScalePkF16toFP8 = make_dummy_class(f"{_P}.VCvtScalePkF16toFP8")
# logicalIR: VCvtScalePkF16toBF8  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCvtScalePkF16toBF8 = make_dummy_class(f"{_P}.VCvtScalePkF16toBF8")
# logicalIR: VCvtScaleSRF16toFP8  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCvtScaleSRF16toFP8 = make_dummy_class(f"{_P}.VCvtScaleSRF16toFP8")
# logicalIR: VCvtScaleSRF16toBF8  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCvtScaleSRF16toBF8 = make_dummy_class(f"{_P}.VCvtScaleSRF16toBF8")
# logicalIR: VCvtPkF32toFP8  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCvtPkF32toFP8 = make_dummy_class(f"{_P}.VCvtPkF32toFP8")
PVCvtBF16toFP32 = make_dummy_class(f"{_P}.PVCvtBF16toFP32")
# logicalIR: VCvtPkF32toBF16  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
VCvtPkF32toBF16 = make_dummy_class(f"{_P}.VCvtPkF32toBF16")


# ==========================================================================
# Memory (Buffer/Flat/Global/DS/SMEM) instructions
# source: rocisa/rocisa/src/instruction/mem.cpp
# ==========================================================================
ReadWriteInstruction = make_dummy_class(f"{_P}.ReadWriteInstruction")
GlobalReadInstruction = make_dummy_class(f"{_P}.GlobalReadInstruction")
FLATReadInstruction = make_dummy_class(f"{_P}.FLATReadInstruction")
GLOBALLoadInstruction = make_dummy_class(f"{_P}.GLOBALLoadInstruction")
MUBUFReadInstruction = make_dummy_class(f"{_P}.MUBUFReadInstruction")
AtomicReadWriteInstruction = make_dummy_class(f"{_P}.AtomicReadWriteInstruction")
SMemAtomicDecInstruction = make_dummy_class(f"{_P}.SMemAtomicDecInstruction")
SMemLoadInstruction = make_dummy_class(f"{_P}.SMemLoadInstruction")
GlobalWriteInstruction = make_dummy_class(f"{_P}.GlobalWriteInstruction")
SMemStoreInstruction = make_dummy_class(f"{_P}.SMemStoreInstruction")
FLATStoreInstruction = make_dummy_class(f"{_P}.FLATStoreInstruction")
MUBUFStoreInstruction = make_dummy_class(f"{_P}.MUBUFStoreInstruction")
LocalReadInstruction = make_dummy_class(f"{_P}.LocalReadInstruction")
DSLoadInstruction = make_dummy_class(f"{_P}.DSLoadInstruction")
LocalWriteInstruction = make_dummy_class(f"{_P}.LocalWriteInstruction")
DSStoreInstruction = make_dummy_class(f"{_P}.DSStoreInstruction")
# logicalIR: BufferLoadU8  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
BufferLoadU8 = make_dummy_class(f"{_P}.BufferLoadU8")
# logicalIR: BufferLoadD16HIU8  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
BufferLoadD16HIU8 = make_dummy_class(f"{_P}.BufferLoadD16HIU8")
# logicalIR: BufferLoadD16U8  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
BufferLoadD16U8 = make_dummy_class(f"{_P}.BufferLoadD16U8")
# logicalIR: BufferLoadD16HIB16  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
BufferLoadD16HIB16 = make_dummy_class(f"{_P}.BufferLoadD16HIB16")
# logicalIR: BufferLoadD16B16  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
BufferLoadD16B16 = make_dummy_class(f"{_P}.BufferLoadD16B16")
# logicalIR: BufferLoadB32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
BufferLoadB32 = make_dummy_class(f"{_P}.BufferLoadB32")
# logicalIR: BufferLoadB64  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
BufferLoadB64 = make_dummy_class(f"{_P}.BufferLoadB64")
# logicalIR: BufferLoadB96  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
BufferLoadB96 = make_dummy_class(f"{_P}.BufferLoadB96")
# logicalIR: BufferLoadB128  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
BufferLoadB128 = make_dummy_class(f"{_P}.BufferLoadB128")
BufferLoadB192 = make_dummy_class(f"{_P}.BufferLoadB192")
# logicalIR: FlatLoadD16HIU8  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
FlatLoadD16HIU8 = make_dummy_class(f"{_P}.FlatLoadD16HIU8")
# logicalIR: FlatLoadD16U8  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
FlatLoadD16U8 = make_dummy_class(f"{_P}.FlatLoadD16U8")
# logicalIR: FlatLoadD16HIB16  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
FlatLoadD16HIB16 = make_dummy_class(f"{_P}.FlatLoadD16HIB16")
# logicalIR: FlatLoadD16B16  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
FlatLoadD16B16 = make_dummy_class(f"{_P}.FlatLoadD16B16")
# logicalIR: FlatLoadB32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
FlatLoadB32 = make_dummy_class(f"{_P}.FlatLoadB32")
# logicalIR: FlatLoadB64  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
FlatLoadB64 = make_dummy_class(f"{_P}.FlatLoadB64")
# logicalIR: FlatLoadB128  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
FlatLoadB128 = make_dummy_class(f"{_P}.FlatLoadB128")
FlatLoadB192 = make_dummy_class(f"{_P}.FlatLoadB192")
GlobalLoadTR8B64 = make_dummy_class(f"{_P}.GlobalLoadTR8B64")
GlobalLoadTR16B128 = make_dummy_class(f"{_P}.GlobalLoadTR16B128")
# logicalIR: BufferStoreB8  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
BufferStoreB8 = make_dummy_class(f"{_P}.BufferStoreB8")
# logicalIR: BufferStoreD16HIU8  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
BufferStoreD16HIU8 = make_dummy_class(f"{_P}.BufferStoreD16HIU8")
BufferStoreD16U8 = make_dummy_class(f"{_P}.BufferStoreD16U8")
# logicalIR: BufferStoreD16HIB16  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
BufferStoreD16HIB16 = make_dummy_class(f"{_P}.BufferStoreD16HIB16")
BufferStoreD16B16 = make_dummy_class(f"{_P}.BufferStoreD16B16")
# logicalIR: BufferStoreB16  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
BufferStoreB16 = make_dummy_class(f"{_P}.BufferStoreB16")
# logicalIR: BufferStoreB32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
BufferStoreB32 = make_dummy_class(f"{_P}.BufferStoreB32")
# logicalIR: BufferStoreB64  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
BufferStoreB64 = make_dummy_class(f"{_P}.BufferStoreB64")
# logicalIR: BufferStoreB128  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
BufferStoreB128 = make_dummy_class(f"{_P}.BufferStoreB128")
# logicalIR: BufferAtomicAddF32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
BufferAtomicAddF32 = make_dummy_class(f"{_P}.BufferAtomicAddF32")
# logicalIR: BufferAtomicCmpswapB32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
BufferAtomicCmpswapB32 = make_dummy_class(f"{_P}.BufferAtomicCmpswapB32")
# logicalIR: BufferAtomicCmpswapB64  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
BufferAtomicCmpswapB64 = make_dummy_class(f"{_P}.BufferAtomicCmpswapB64")
# logicalIR: FlatStoreD16HIB16  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
FlatStoreD16HIB16 = make_dummy_class(f"{_P}.FlatStoreD16HIB16")
FlatStoreD16B16 = make_dummy_class(f"{_P}.FlatStoreD16B16")
# logicalIR: FlatStoreB32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
FlatStoreB32 = make_dummy_class(f"{_P}.FlatStoreB32")
# logicalIR: FlatStoreB64  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
FlatStoreB64 = make_dummy_class(f"{_P}.FlatStoreB64")
# logicalIR: FlatStoreB128  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
FlatStoreB128 = make_dummy_class(f"{_P}.FlatStoreB128")
# logicalIR: FlatAtomicCmpswapB32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
FlatAtomicCmpswapB32 = make_dummy_class(f"{_P}.FlatAtomicCmpswapB32")
# logicalIR: DSLoadU8  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
DSLoadU8 = make_dummy_class(f"{_P}.DSLoadU8")
DSLoadD16HIU8 = make_dummy_class(f"{_P}.DSLoadD16HIU8")
# logicalIR: DSLoadU16  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
DSLoadU16 = make_dummy_class(f"{_P}.DSLoadU16")
DSLoadD16HIU16 = make_dummy_class(f"{_P}.DSLoadD16HIU16")
DSLoadB16 = make_dummy_class(f"{_P}.DSLoadB16")
# logicalIR: DSLoadB32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
DSLoadB32 = make_dummy_class(f"{_P}.DSLoadB32")
# logicalIR: DSLoadB64  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
DSLoadB64 = make_dummy_class(f"{_P}.DSLoadB64")
DSLoadB96TrB6 = make_dummy_class(f"{_P}.DSLoadB96TrB6")
DSLoadB64TrB4 = make_dummy_class(f"{_P}.DSLoadB64TrB4")
DSLoadB64TrB16 = make_dummy_class(f"{_P}.DSLoadB64TrB16")
DSLoadB128TrB16 = make_dummy_class(f"{_P}.DSLoadB128TrB16")
DSLoadB64TrB8 = make_dummy_class(f"{_P}.DSLoadB64TrB8")
# logicalIR: DSLoadB128  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
DSLoadB128 = make_dummy_class(f"{_P}.DSLoadB128")
DSLoadB192 = make_dummy_class(f"{_P}.DSLoadB192")
# logicalIR: DSLoad2B32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
DSLoad2B32 = make_dummy_class(f"{_P}.DSLoad2B32")
# logicalIR: DSLoad2B64  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
DSLoad2B64 = make_dummy_class(f"{_P}.DSLoad2B64")
DSStoreU16 = make_dummy_class(f"{_P}.DSStoreU16")
# logicalIR: DSStoreB8  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
DSStoreB8 = make_dummy_class(f"{_P}.DSStoreB8")
# logicalIR: DSStoreB16  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
DSStoreB16 = make_dummy_class(f"{_P}.DSStoreB16")
DSStoreB8HID16 = make_dummy_class(f"{_P}.DSStoreB8HID16")
DSStoreD16HIB16 = make_dummy_class(f"{_P}.DSStoreD16HIB16")
# logicalIR: DSStoreB32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
DSStoreB32 = make_dummy_class(f"{_P}.DSStoreB32")
# logicalIR: DSStoreB64  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
DSStoreB64 = make_dummy_class(f"{_P}.DSStoreB64")
# logicalIR: DSStoreB96  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
DSStoreB96 = make_dummy_class(f"{_P}.DSStoreB96")
# logicalIR: DSStoreB128  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
DSStoreB128 = make_dummy_class(f"{_P}.DSStoreB128")
DSStoreB192 = make_dummy_class(f"{_P}.DSStoreB192")
DSStoreB256 = make_dummy_class(f"{_P}.DSStoreB256")
# logicalIR: DSStore2B32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
DSStore2B32 = make_dummy_class(f"{_P}.DSStore2B32")
# logicalIR: DSStore2B64  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
DSStore2B64 = make_dummy_class(f"{_P}.DSStore2B64")
# logicalIR: DSBPermuteB32  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
DSBPermuteB32 = make_dummy_class(f"{_P}.DSBPermuteB32")
SAtomicDec = make_dummy_class(f"{_P}.SAtomicDec")
SLoadB32 = make_dummy_class(f"{_P}.SLoadB32")
SLoadB64 = make_dummy_class(f"{_P}.SLoadB64")
SLoadB128 = make_dummy_class(f"{_P}.SLoadB128")
SLoadB256 = make_dummy_class(f"{_P}.SLoadB256")
SLoadB512 = make_dummy_class(f"{_P}.SLoadB512")
SStoreB32 = make_dummy_class(f"{_P}.SStoreB32")
SStoreB64 = make_dummy_class(f"{_P}.SStoreB64")
SStoreB128 = make_dummy_class(f"{_P}.SStoreB128")
SStoreB256 = make_dummy_class(f"{_P}.SStoreB256")
SStoreB512 = make_dummy_class(f"{_P}.SStoreB512")
# logicalIR: TensorLoadToLds  (see shared/stinkytofu/src/ir/logical/LogicalInstructionDefs.inc)
TensorLoadToLds = make_dummy_class(f"{_P}.TensorLoadToLds")


# ==========================================================================
# MFMA / SMFMA / MXMFMA instructions
# source: rocisa/rocisa/src/instruction/mfma.cpp
# ==========================================================================
MFMAInstruction = make_dummy_class(f"{_P}.MFMAInstruction")
MXMFMAInstruction = make_dummy_class(f"{_P}.MXMFMAInstruction")
SMFMAInstruction = make_dummy_class(f"{_P}.SMFMAInstruction")
getMFMAIssueLatency = make_dummy_func(f"{_P}.getMFMAIssueLatency")
getSMFMAIssueLatency = make_dummy_func(f"{_P}.getSMFMAIssueLatency")


# ==========================================================================
# Extension helpers (exposed as functions)
# source: rocisa/rocisa/src/instruction/extension.cpp
# ==========================================================================
SLongBranch = make_dummy_func(f"{_P}.SLongBranch")
SGetPositivePCOffset = make_dummy_func(f"{_P}.SGetPositivePCOffset")
SLongBranchPositive = make_dummy_func(f"{_P}.SLongBranchPositive")
SLongBranchNegative = make_dummy_func(f"{_P}.SLongBranchNegative")
SCLongBranchScc0 = make_dummy_func(f"{_P}.SCLongBranchScc0")
SCLongBranchScc1 = make_dummy_func(f"{_P}.SCLongBranchScc1")
SCLongBranchVccnz = make_dummy_func(f"{_P}.SCLongBranchVccnz")
SMulInt64to32 = make_dummy_func(f"{_P}.SMulInt64to32")
VCvtBF16toFP32 = make_dummy_func(f"{_P}.VCvtBF16toFP32")

