// Copyright © Advanced Micro Devices, Inc., or its affiliates.
// SPDX-License-Identifier: MIT

#pragma once

#include "HipdnnAttentionImplementation.h"
#include "HipdnnBackendAttributeName.h"
#include "HipdnnBackendAttributeType.h"
#include "HipdnnBackendBehaviorNote.h"
#include "HipdnnBackendDescriptorType.h"
#include "HipdnnBackendPluginLoadingMode.h"
#include "HipdnnBackendPluginUnloadingMode.h"
#include "HipdnnConvolutionMode.h"
#include "HipdnnDataType.h"
#include "HipdnnDiagonalAlignment.h"
#include "HipdnnNormFwdPhase.h"
#include "HipdnnOperationType.h"
#include "HipdnnPointwiseMode.h"
#include "HipdnnReduceTensorOp.h"
#include "HipdnnStatus.h"

namespace hipdnn_backend
{

inline const char* hipdnnGetStatusString(hipdnnStatus_t status)
{
    switch(status)
    {
    case HIPDNN_STATUS_SUCCESS:
        return "HIPDNN_STATUS_SUCCESS";
    case HIPDNN_STATUS_NOT_INITIALIZED:
        return "HIPDNN_STATUS_NOT_INITIALIZED";
    case HIPDNN_STATUS_BAD_PARAM:
        return "HIPDNN_STATUS_BAD_PARAM";
    case HIPDNN_STATUS_BAD_PARAM_NULL_POINTER:
        return "HIPDNN_STATUS_BAD_PARAM_NULL_POINTER";
    case HIPDNN_STATUS_BAD_PARAM_NOT_FINALIZED:
        return "HIPDNN_STATUS_BAD_PARAM_NOT_FINALIZED";
    case HIPDNN_STATUS_BAD_PARAM_OUT_OF_BOUND:
        return "HIPDNN_STATUS_BAD_PARAM_OUT_OF_BOUND";
    case HIPDNN_STATUS_BAD_PARAM_SIZE_INSUFFICIENT:
        return "HIPDNN_STATUS_BAD_PARAM_SIZE_INSUFFICIENT";
    case HIPDNN_STATUS_BAD_PARAM_STREAM_MISMATCH:
        return "HIPDNN_STATUS_BAD_PARAM_STREAM_MISMATCH";
    case HIPDNN_STATUS_NOT_SUPPORTED:
        return "HIPDNN_STATUS_NOT_SUPPORTED";
    case HIPDNN_STATUS_INTERNAL_ERROR:
        return "HIPDNN_STATUS_INTERNAL_ERROR";
    case HIPDNN_STATUS_ALLOC_FAILED:
        return "HIPDNN_STATUS_ALLOC_FAILED";
    case HIPDNN_STATUS_INTERNAL_ERROR_HOST_ALLOCATION_FAILED:
        return "HIPDNN_STATUS_INTERNAL_ERROR_HOST_ALLOCATION_FAILED";
    case HIPDNN_STATUS_INTERNAL_ERROR_DEVICE_ALLOCATION_FAILED:
        return "HIPDNN_STATUS_INTERNAL_ERROR_DEVICE_ALLOCATION_FAILED";
    case HIPDNN_STATUS_EXECUTION_FAILED:
        return "HIPDNN_STATUS_EXECUTION_FAILED";
    default:
        return "HIPDNN_STATUS_UNKNOWN";
    }
}

inline const char* hipdnnGetDataTypeString(hipdnnDataType_t type)
{
    switch(type)
    {
    case HIPDNN_DATA_FLOAT:
        return "HIPDNN_DATA_FLOAT";
    case HIPDNN_DATA_DOUBLE:
        return "HIPDNN_DATA_DOUBLE";
    case HIPDNN_DATA_HALF:
        return "HIPDNN_DATA_HALF";
    case HIPDNN_DATA_INT8:
        return "HIPDNN_DATA_INT8";
    case HIPDNN_DATA_INT32:
        return "HIPDNN_DATA_INT32";
    case HIPDNN_DATA_UINT8:
        return "HIPDNN_DATA_UINT8";
    case HIPDNN_DATA_BFLOAT16:
        return "HIPDNN_DATA_BFLOAT16";
    case HIPDNN_DATA_FP8_E4M3:
        return "HIPDNN_DATA_FP8_E4M3";
    case HIPDNN_DATA_FP8_E5M2:
        return "HIPDNN_DATA_FP8_E5M2";
    case HIPDNN_DATA_FP8_E4M3_FNUZ:
        return "HIPDNN_DATA_FP8_E4M3_FNUZ";
    case HIPDNN_DATA_FP8_E5M2_FNUZ:
        return "HIPDNN_DATA_FP8_E5M2_FNUZ";
    case HIPDNN_DATA_FP8_E8M0:
        return "HIPDNN_DATA_FP8_E8M0";
    case HIPDNN_DATA_FP4_E2M1:
        return "HIPDNN_DATA_FP4_E2M1";
    case HIPDNN_DATA_INT4:
        return "HIPDNN_DATA_INT4";
    case HIPDNN_DATA_FP6_E2M3_EXT:
        return "HIPDNN_DATA_FP6_E2M3_EXT";
    case HIPDNN_DATA_FP6_E3M2_EXT:
        return "HIPDNN_DATA_FP6_E3M2_EXT";
    case HIPDNN_DATA_INT64:
        return "HIPDNN_DATA_INT64";
    case HIPDNN_DATA_BOOLEAN:
        return "HIPDNN_DATA_BOOLEAN";
    default:
        return "HIPDNN_DATA_UNKNOWN";
    }
}

inline const char* hipdnnGetAttributeTypeString(hipdnnBackendAttributeType_t type)
{
    switch(type)
    {
    case HIPDNN_TYPE_HANDLE:
        return "HIPDNN_TYPE_HANDLE";
    case HIPDNN_TYPE_DATA_TYPE:
        return "HIPDNN_TYPE_DATA_TYPE";
    case HIPDNN_TYPE_BOOLEAN:
        return "HIPDNN_TYPE_BOOLEAN";
    case HIPDNN_TYPE_INT64:
        return "HIPDNN_TYPE_INT64";
    case HIPDNN_TYPE_FLOAT:
        return "HIPDNN_TYPE_FLOAT";
    case HIPDNN_TYPE_DOUBLE:
        return "HIPDNN_TYPE_DOUBLE";
    case HIPDNN_TYPE_VOID_PTR:
        return "HIPDNN_TYPE_VOID_PTR";
    case HIPDNN_TYPE_HEUR_MODE:
        return "HIPDNN_TYPE_HEUR_MODE";
    case HIPDNN_TYPE_KNOB_TYPE:
        return "HIPDNN_TYPE_KNOB_TYPE";
    case HIPDNN_TYPE_NAN_PROPOGATION:
        return "HIPDNN_TYPE_NAN_PROPOGATION";
    case HIPDNN_TYPE_NUMERICAL_NOTE:
        return "HIPDNN_TYPE_NUMERICAL_NOTE";
    case HIPDNN_TYPE_LAYOUT_TYPE:
        return "HIPDNN_TYPE_LAYOUT_TYPE";
    case HIPDNN_TYPE_ATTRIB_NAME:
        return "HIPDNN_TYPE_ATTRIB_NAME";
    case HIPDNN_TYPE_BACKEND_DESCRIPTOR:
        return "HIPDNN_TYPE_BACKEND_DESCRIPTOR";
    case HIPDNN_TYPE_GENSTATS_MODE:
        return "HIPDNN_TYPE_GENSTATS_MODE";
    case HIPDNN_TYPE_BN_FINALIZE_STATS_MODE:
        return "HIPDNN_TYPE_BN_FINALIZE_STATS_MODE";
    case HIPDNN_TYPE_BEHAVIOR_NOTE:
        return "HIPDNN_TYPE_BEHAVIOR_NOTE";
    case HIPDNN_TYPE_TENSOR_REORDERING_MODE:
        return "HIPDNN_TYPE_TENSOR_REORDERING_MODE";
    case HIPDNN_TYPE_INT32:
        return "HIPDNN_TYPE_INT32";
    case HIPDNN_TYPE_CHAR:
        return "HIPDNN_TYPE_CHAR";
    case HIPDNN_TYPE_SIGNAL_MODE:
        return "HIPDNN_TYPE_SIGNAL_MODE";
    case HIPDNN_TYPE_FRACTION:
        return "HIPDNN_TYPE_FRACTION";
    case HIPDNN_TYPE_NORM_FWD_PHASE:
        return "HIPDNN_TYPE_NORM_FWD_PHASE";
    case HIPDNN_TYPE_RNG_DISTRIBUTION:
        return "HIPDNN_TYPE_RNG_DISTRIBUTION";
    case HIPDNN_TYPE_CONVOLUTION_MODE:
        return "HIPDNN_TYPE_CONVOLUTION_MODE";
    case HIPDNN_TYPE_POINTWISE_MODE:
        return "HIPDNN_TYPE_POINTWISE_MODE";

    // Extension API
    case HIPDNN_TYPE_FLATBUFFER_DATA_STRUCT_EXT:
        return "HIPDNN_TYPE_FLATBUFFER_DATA_STRUCT_EXT";
    case HIPDNN_TYPE_DIAGONAL_ALIGNMENT_EXT:
        return "HIPDNN_TYPE_DIAGONAL_ALIGNMENT_EXT";
    case HIPDNN_TYPE_ATTENTION_IMPLEMENTATION_EXT:
        return "HIPDNN_TYPE_ATTENTION_IMPLEMENTATION_EXT";
    case HIPDNN_TYPE_REDUCTION_OPERATOR_TYPE:
        return "HIPDNN_TYPE_REDUCTION_OPERATOR_TYPE";
    case HIPDNN_TYPE_RESAMPLE_MODE:
        return "HIPDNN_TYPE_RESAMPLE_MODE";
    case HIPDNN_TYPE_PADDING_MODE:
        return "HIPDNN_TYPE_PADDING_MODE";

    default:
        return "HIPDNN_ATTRIBUTE_UNKNOWN";
    }
}

inline const char* hipdnnGetBehaviorNoteString(hipdnnBackendBehaviorNote_t note)
{
    switch(note)
    {
    case HIPDNN_BEHAVIOR_NOTE_RUNTIME_COMPILATION:
        return "HIPDNN_BEHAVIOR_NOTE_RUNTIME_COMPILATION";
    case HIPDNN_BEHAVIOR_NOTE_REQUIRES_LAYOUT_TRANSFORM:
        return "HIPDNN_BEHAVIOR_NOTE_REQUIRES_LAYOUT_TRANSFORM";
    case HIPDNN_BEHAVIOR_NOTE_SUPPORTS_GRAPH_CAPTURE:
        return "HIPDNN_BEHAVIOR_NOTE_SUPPORTS_GRAPH_CAPTURE";
    case HIPDNN_BEHAVIOR_NOTE_EXTERNAL_LIBRARY_DEPENDENCY:
        return "HIPDNN_BEHAVIOR_NOTE_EXTERNAL_LIBRARY_DEPENDENCY";
    case HIPDNN_BEHAVIOR_NOTE_SUPPORTS_EXECUTION_PLAN_SERIALIZATION:
        return "HIPDNN_BEHAVIOR_NOTE_SUPPORTS_EXECUTION_PLAN_SERIALIZATION";
    case HIPDNN_BEHAVIOR_NOTE_TYPE_COUNT:
        return "HIPDNN_BEHAVIOR_NOTE_TYPE_COUNT";
    default:
        return "HIPDNN_BEHAVIOR_NOTE_UNKNOWN";
    }
}

inline const char* hipdnnGetBackendDescriptorTypeName(hipdnnBackendDescriptorType_t type)
{
    switch(type)
    {
    case HIPDNN_BACKEND_ENGINE_DESCRIPTOR:
        return "HIPDNN_BACKEND_ENGINE_DESCRIPTOR";
    case HIPDNN_BACKEND_ENGINECFG_DESCRIPTOR:
        return "HIPDNN_BACKEND_ENGINECFG_DESCRIPTOR";
    case HIPDNN_BACKEND_ENGINEHEUR_DESCRIPTOR:
        return "HIPDNN_BACKEND_ENGINEHEUR_DESCRIPTOR";
    case HIPDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR:
        return "HIPDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR";
    case HIPDNN_BACKEND_INTERMEDIATE_INFO_DESCRIPTOR:
        return "HIPDNN_BACKEND_INTERMEDIATE_INFO_DESCRIPTOR";
    case HIPDNN_BACKEND_KNOB_CHOICE_DESCRIPTOR:
        return "HIPDNN_BACKEND_KNOB_CHOICE_DESCRIPTOR";
    case HIPDNN_BACKEND_KNOB_INFO_DESCRIPTOR:
        return "HIPDNN_BACKEND_KNOB_INFO_DESCRIPTOR";
    case HIPDNN_BACKEND_LAYOUT_INFO_DESCRIPTOR:
        return "HIPDNN_BACKEND_LAYOUT_INFO_DESCRIPTOR";
    case HIPDNN_BACKEND_OPERATION_GEN_STATS_DESCRIPTOR:
        return "HIPDNN_BACKEND_OPERATION_GEN_STATS_DESCRIPTOR";
    case HIPDNN_BACKEND_OPERATIONGRAPH_DESCRIPTOR:
        return "HIPDNN_BACKEND_OPERATIONGRAPH_DESCRIPTOR";
    case HIPDNN_BACKEND_VARIANT_PACK_DESCRIPTOR:
        return "HIPDNN_BACKEND_VARIANT_PACK_DESCRIPTOR";
    case HIPDNN_BACKEND_KERNEL_CACHE_DESCRIPTOR:
        return "HIPDNN_BACKEND_KERNEL_CACHE_DESCRIPTOR";
    case HIPDNN_BACKEND_OPERATION_PAGED_CACHE_LOAD_DESCRIPTOR:
        return "HIPDNN_BACKEND_OPERATION_PAGED_CACHE_LOAD_DESCRIPTOR";
    case HIPDNN_BACKEND_TENSOR_DESCRIPTOR:
        return "HIPDNN_BACKEND_TENSOR_DESCRIPTOR";
    case HIPDNN_BACKEND_OPERATION_CONVOLUTION_FORWARD_DESCRIPTOR:
        return "HIPDNN_BACKEND_OPERATION_CONVOLUTION_FORWARD_DESCRIPTOR";
    case HIPDNN_BACKEND_OPERATION_CONVOLUTION_BACKWARD_FILTER_DESCRIPTOR:
        return "HIPDNN_BACKEND_OPERATION_CONVOLUTION_BACKWARD_FILTER_DESCRIPTOR";
    case HIPDNN_BACKEND_OPERATION_BATCHNORM_INFERENCE_DESCRIPTOR_EXT:
        return "HIPDNN_BACKEND_OPERATION_BATCHNORM_INFERENCE_DESCRIPTOR_EXT";
    case HIPDNN_BACKEND_OPERATION_POINTWISE_DESCRIPTOR:
        return "HIPDNN_BACKEND_OPERATION_POINTWISE_DESCRIPTOR";
    case HIPDNN_BACKEND_OPERATION_CONVOLUTION_BACKWARD_DATA_DESCRIPTOR:
        return "HIPDNN_BACKEND_OPERATION_CONVOLUTION_BACKWARD_DATA_DESCRIPTOR";
    case HIPDNN_BACKEND_OPERATION_BATCHNORM_BACKWARD_DESCRIPTOR_EXT:
        return "HIPDNN_BACKEND_OPERATION_BATCHNORM_BACKWARD_DESCRIPTOR_EXT";
    case HIPDNN_BACKEND_OPERATION_BATCHNORM_INFERENCE_VARIANCE_DESCRIPTOR_EXT:
        return "HIPDNN_BACKEND_OPERATION_BATCHNORM_INFERENCE_VARIANCE_DESCRIPTOR_EXT";
    case HIPDNN_BACKEND_OPERATION_MATMUL_DESCRIPTOR:
        return "HIPDNN_BACKEND_OPERATION_MATMUL_DESCRIPTOR";
    case HIPDNN_BACKEND_OPERATION_RMSNORM_DESCRIPTOR_EXT:
        return "HIPDNN_BACKEND_OPERATION_RMSNORM_DESCRIPTOR_EXT";
    case HIPDNN_BACKEND_OPERATION_SDPA_FWD_DESCRIPTOR:
        return "HIPDNN_BACKEND_OPERATION_SDPA_FWD_DESCRIPTOR";
    case HIPDNN_BACKEND_OPERATION_LAYERNORM_DESCRIPTOR_EXT:
        return "HIPDNN_BACKEND_OPERATION_LAYERNORM_DESCRIPTOR_EXT";
    case HIPDNN_BACKEND_OPERATION_BLOCK_SCALE_QUANTIZE_DESCRIPTOR:
        return "HIPDNN_BACKEND_OPERATION_BLOCK_SCALE_QUANTIZE_DESCRIPTOR";
    case HIPDNN_BACKEND_OPERATION_BATCHNORM_DESCRIPTOR_EXT:
        return "HIPDNN_BACKEND_OPERATION_BATCHNORM_DESCRIPTOR_EXT";
    case HIPDNN_BACKEND_OPERATION_BLOCK_SCALE_DEQUANTIZE_DESCRIPTOR:
        return "HIPDNN_BACKEND_OPERATION_BLOCK_SCALE_DEQUANTIZE_DESCRIPTOR";
    case HIPDNN_BACKEND_OPERATION_CUSTOM_OP_DESCRIPTOR_EXT:
        return "HIPDNN_BACKEND_OPERATION_CUSTOM_OP_DESCRIPTOR_EXT";
    case HIPDNN_BACKEND_OPERATION_SDPA_BWD_DESCRIPTOR_EXT:
        return "HIPDNN_BACKEND_OPERATION_SDPA_BWD_DESCRIPTOR_EXT";
    case HIPDNN_BACKEND_OPERATION_REDUCTION_DESCRIPTOR:
        return "HIPDNN_BACKEND_OPERATION_REDUCTION_DESCRIPTOR";
    case HIPDNN_BACKEND_OPERATION_RESAMPLE_FWD_DESCRIPTOR:
        return "HIPDNN_BACKEND_OPERATION_RESAMPLE_FWD_DESCRIPTOR";
    case HIPDNN_BACKEND_OPERATION_RMSNORM_BACKWARD_DESCRIPTOR_EXT:
        return "HIPDNN_BACKEND_OPERATION_RMSNORM_BACKWARD_DESCRIPTOR_EXT";
    default:
        return "UNKNOWN_TYPE";
    }
}

inline const char* hipdnnGetAttributeNameString(hipdnnBackendAttributeName_t attr)
{
    switch(attr)
    {
    case HIPDNN_ATTR_ENGINEHEUR_MODE:
        return "HIPDNN_ATTR_ENGINEHEUR_MODE";
    case HIPDNN_ATTR_ENGINEHEUR_OPERATION_GRAPH:
        return "HIPDNN_ATTR_ENGINEHEUR_OPERATION_GRAPH";
    case HIPDNN_ATTR_ENGINEHEUR_RESULTS:
        return "HIPDNN_ATTR_ENGINEHEUR_RESULTS";
    case HIPDNN_ATTR_ENGINEHEUR_SM_COUNT_TARGET:
        return "HIPDNN_ATTR_ENGINEHEUR_SM_COUNT_TARGET";
    case HIPDNN_ATTR_ENGINEHEUR_DEVICEPROP:
        return "HIPDNN_ATTR_ENGINEHEUR_DEVICEPROP";
    case HIPDNN_ATTR_ENGINEHEUR_FIND_FIRST_EXT:
        return "HIPDNN_ATTR_ENGINEHEUR_FIND_FIRST_EXT";

    case HIPDNN_ATTR_ENGINECFG_ENGINE:
        return "HIPDNN_ATTR_ENGINECFG_ENGINE";
    case HIPDNN_ATTR_ENGINECFG_INTERMEDIATE_INFO:
        return "HIPDNN_ATTR_ENGINECFG_INTERMEDIATE_INFO";
    case HIPDNN_ATTR_ENGINECFG_KNOB_CHOICES:
        return "HIPDNN_ATTR_ENGINECFG_KNOB_CHOICES";
    case HIPDNN_ATTR_ENGINECFG_WORKSPACE_SIZE:
        return "HIPDNN_ATTR_ENGINECFG_WORKSPACE_SIZE";

    case HIPDNN_ATTR_EXECUTION_PLAN_HANDLE:
        return "HIPDNN_ATTR_EXECUTION_PLAN_HANDLE";
    case HIPDNN_ATTR_EXECUTION_PLAN_ENGINE_CONFIG:
        return "HIPDNN_ATTR_EXECUTION_PLAN_ENGINE_CONFIG";
    case HIPDNN_ATTR_EXECUTION_PLAN_WORKSPACE_SIZE:
        return "HIPDNN_ATTR_EXECUTION_PLAN_WORKSPACE_SIZE";
    case HIPDNN_ATTR_EXECUTION_PLAN_COMPUTED_INTERMEDIATE_UIDS:
        return "HIPDNN_ATTR_EXECUTION_PLAN_COMPUTED_INTERMEDIATE_UIDS";
    case HIPDNN_ATTR_EXECUTION_PLAN_RUN_ONLY_INTERMEDIATE_UIDS:
        return "HIPDNN_ATTR_EXECUTION_PLAN_RUN_ONLY_INTERMEDIATE_UIDS";
    case HIPDNN_ATTR_EXECUTION_PLAN_JSON_REPRESENTATION:
        return "HIPDNN_ATTR_EXECUTION_PLAN_JSON_REPRESENTATION";
    case HIPDNN_ATTR_EXECUTION_PLAN_KERNEL_CACHE:
        return "HIPDNN_ATTR_EXECUTION_PLAN_KERNEL_CACHE";
    case HIPDNN_ATTR_EXECUTION_PLAN_DEVICEPROP:
        return "HIPDNN_ATTR_EXECUTION_PLAN_DEVICEPROP";
    case HIPDNN_ATTR_EXECUTION_PLAN_TENSOR_UIDS_EXT:
        return "HIPDNN_ATTR_EXECUTION_PLAN_TENSOR_UIDS_EXT";

    case HIPDNN_ATTR_INTERMEDIATE_INFO_UNIQUE_ID:
        return "HIPDNN_ATTR_INTERMEDIATE_INFO_UNIQUE_ID";
    case HIPDNN_ATTR_INTERMEDIATE_INFO_SIZE:
        return "HIPDNN_ATTR_INTERMEDIATE_INFO_SIZE";
    case HIPDNN_ATTR_INTERMEDIATE_INFO_DEPENDENT_DATA_UIDS:
        return "HIPDNN_ATTR_INTERMEDIATE_INFO_DEPENDENT_DATA_UIDS";
    case HIPDNN_ATTR_INTERMEDIATE_INFO_DEPENDENT_ATTRIBUTES:
        return "HIPDNN_ATTR_INTERMEDIATE_INFO_DEPENDENT_ATTRIBUTES";

    case HIPDNN_ATTR_KNOB_CHOICE_KNOB_TYPE:
        return "HIPDNN_ATTR_KNOB_CHOICE_KNOB_TYPE";
    case HIPDNN_ATTR_KNOB_CHOICE_KNOB_VALUE:
        return "HIPDNN_ATTR_KNOB_CHOICE_KNOB_VALUE";

    case HIPDNN_ATTR_OPERATIONGRAPH_HANDLE:
        return "HIPDNN_ATTR_OPERATIONGRAPH_HANDLE";
    case HIPDNN_ATTR_OPERATIONGRAPH_OPS:
        return "HIPDNN_ATTR_OPERATIONGRAPH_OPS";
    case HIPDNN_ATTR_OPERATIONGRAPH_ENGINE_GLOBAL_COUNT:
        return "HIPDNN_ATTR_OPERATIONGRAPH_ENGINE_GLOBAL_COUNT";
    case HIPDNN_ATTR_OPERATIONGRAPH_IS_DYNAMIC_SHAPE_ENABLED:
        return "HIPDNN_ATTR_OPERATIONGRAPH_IS_DYNAMIC_SHAPE_ENABLED";
    case HIPDNN_ATTR_OPERATIONGRAPH_COMPUTE_DATA_TYPE_EXT:
        return "HIPDNN_ATTR_OPERATIONGRAPH_COMPUTE_DATA_TYPE_EXT";
    case HIPDNN_ATTR_OPERATIONGRAPH_INTERMEDIATE_DATA_TYPE_EXT:
        return "HIPDNN_ATTR_OPERATIONGRAPH_INTERMEDIATE_DATA_TYPE_EXT";
    case HIPDNN_ATTR_OPERATIONGRAPH_IO_DATA_TYPE_EXT:
        return "HIPDNN_ATTR_OPERATIONGRAPH_IO_DATA_TYPE_EXT";
    case HIPDNN_ATTR_OPERATIONGRAPH_PREFERRED_ENGINE_ID_EXT:
        return "HIPDNN_ATTR_OPERATIONGRAPH_PREFERRED_ENGINE_ID_EXT";
    case HIPDNN_ATTR_OPERATIONGRAPH_NAME_EXT:
        return "HIPDNN_ATTR_OPERATIONGRAPH_NAME_EXT";

    case HIPDNN_ATTR_VARIANT_PACK_UNIQUE_IDS:
        return "HIPDNN_ATTR_VARIANT_PACK_UNIQUE_IDS";
    case HIPDNN_ATTR_VARIANT_PACK_DATA_POINTERS:
        return "HIPDNN_ATTR_VARIANT_PACK_DATA_POINTERS";
    case HIPDNN_ATTR_VARIANT_PACK_INTERMEDIATES:
        return "HIPDNN_ATTR_VARIANT_PACK_INTERMEDIATES";
    case HIPDNN_ATTR_VARIANT_PACK_WORKSPACE:
        return "HIPDNN_ATTR_VARIANT_PACK_WORKSPACE";

    case HIPDNN_ATTR_LAYOUT_INFO_TENSOR_UID:
        return "HIPDNN_ATTR_LAYOUT_INFO_TENSOR_UID";
    case HIPDNN_ATTR_LAYOUT_INFO_TYPES:
        return "HIPDNN_ATTR_LAYOUT_INFO_TYPES";

    case HIPDNN_ATTR_KNOB_INFO_TYPE:
        return "HIPDNN_ATTR_KNOB_INFO_TYPE";
    case HIPDNN_ATTR_KNOB_INFO_MAXIMUM_VALUE:
        return "HIPDNN_ATTR_KNOB_INFO_MAXIMUM_VALUE";
    case HIPDNN_ATTR_KNOB_INFO_MINIMUM_VALUE:
        return "HIPDNN_ATTR_KNOB_INFO_MINIMUM_VALUE";
    case HIPDNN_ATTR_KNOB_INFO_STRIDE:
        return "HIPDNN_ATTR_KNOB_INFO_STRIDE";
    case HIPDNN_ATTR_KNOB_INFO_DESCRIPTION:
        return "HIPDNN_ATTR_KNOB_INFO_DESCRIPTION";
    case HIPDNN_ATTR_KNOB_INFO_DEFAULT_VALUE:
        return "HIPDNN_ATTR_KNOB_INFO_DEFAULT_VALUE";
    case HIPDNN_ATTR_KNOB_INFO_DEPRECATED:
        return "HIPDNN_ATTR_KNOB_INFO_DEPRECATED";
    case HIPDNN_ATTR_KNOB_INFO_VALID_VALUES_INT:
        return "HIPDNN_ATTR_KNOB_INFO_VALID_VALUES_INT";
    case HIPDNN_ATTR_KNOB_INFO_VALID_VALUES_STRING:
        return "HIPDNN_ATTR_KNOB_INFO_VALID_VALUES_STRING";
    case HIPDNN_ATTR_KNOB_INFO_STRING_MAX_LENGTH:
        return "HIPDNN_ATTR_KNOB_INFO_STRING_MAX_LENGTH";
    case HIPDNN_ATTR_KNOB_INFO_DEFAULT_VALUE_TYPE:
        return "HIPDNN_ATTR_KNOB_INFO_DEFAULT_VALUE_TYPE";

    case HIPDNN_ATTR_ENGINE_OPERATION_GRAPH:
        return "HIPDNN_ATTR_ENGINE_OPERATION_GRAPH";
    case HIPDNN_ATTR_ENGINE_GLOBAL_INDEX:
        return "HIPDNN_ATTR_ENGINE_GLOBAL_INDEX";
    case HIPDNN_ATTR_ENGINE_KNOB_INFO:
        return "HIPDNN_ATTR_ENGINE_KNOB_INFO";
    case HIPDNN_ATTR_ENGINE_NUMERICAL_NOTE:
        return "HIPDNN_ATTR_ENGINE_NUMERICAL_NOTE";
    case HIPDNN_ATTR_ENGINE_LAYOUT_INFO:
        return "HIPDNN_ATTR_ENGINE_LAYOUT_INFO";
    case HIPDNN_ATTR_ENGINE_BEHAVIOR_NOTE:
        return "HIPDNN_ATTR_ENGINE_BEHAVIOR_NOTE";
    case HIPDNN_ATTR_ENGINE_CU_COUNT_TARGET_EXT:
        return "HIPDNN_ATTR_ENGINE_CU_COUNT_TARGET_EXT";
    case HIPDNN_ATTR_ENGINE_DEVICEPROP:
        return "HIPDNN_ATTR_ENGINE_DEVICEPROP";

    case HIPDNN_ATTR_KERNEL_CACHE_IS_ENGINECFG_KERNEL_CACHED:
        return "HIPDNN_ATTR_KERNEL_CACHE_IS_ENGINECFG_KERNEL_CACHED";

    case HIPDNN_ATTR_DEVICEPROP_DEVICE_ID:
        return "HIPDNN_ATTR_DEVICEPROP_DEVICE_ID";
    case HIPDNN_ATTR_DEVICEPROP_HANDLE:
        return "HIPDNN_ATTR_DEVICEPROP_HANDLE";
    case HIPDNN_ATTR_DEVICEPROP_JSON_REPRESENTATION:
        return "HIPDNN_ATTR_DEVICEPROP_JSON_REPRESENTATION";

    // Tensor attributes
    case HIPDNN_ATTR_TENSOR_UNIQUE_ID:
        return "HIPDNN_ATTR_TENSOR_UNIQUE_ID";
    case HIPDNN_ATTR_TENSOR_NAME_EXT:
        return "HIPDNN_ATTR_TENSOR_NAME_EXT";
    case HIPDNN_ATTR_TENSOR_DATA_TYPE:
        return "HIPDNN_ATTR_TENSOR_DATA_TYPE";
    case HIPDNN_ATTR_TENSOR_DIMENSIONS:
        return "HIPDNN_ATTR_TENSOR_DIMENSIONS";
    case HIPDNN_ATTR_TENSOR_STRIDES:
        return "HIPDNN_ATTR_TENSOR_STRIDES";
    case HIPDNN_ATTR_TENSOR_IS_VIRTUAL:
        return "HIPDNN_ATTR_TENSOR_IS_VIRTUAL";
    case HIPDNN_ATTR_TENSOR_VALUE_EXT:
        return "HIPDNN_ATTR_TENSOR_VALUE_EXT";
    case HIPDNN_ATTR_TENSOR_IS_BY_VALUE:
        return "HIPDNN_ATTR_TENSOR_IS_BY_VALUE";

    // Convolution forward operation attributes
    case HIPDNN_ATTR_OPERATION_CONVOLUTION_FORWARD_W:
        return "HIPDNN_ATTR_OPERATION_CONVOLUTION_FORWARD_W";
    case HIPDNN_ATTR_OPERATION_CONVOLUTION_FORWARD_X:
        return "HIPDNN_ATTR_OPERATION_CONVOLUTION_FORWARD_X";
    case HIPDNN_ATTR_OPERATION_CONVOLUTION_FORWARD_Y:
        return "HIPDNN_ATTR_OPERATION_CONVOLUTION_FORWARD_Y";

    // Shared convolution descriptor attributes
    case HIPDNN_ATTR_CONVOLUTION_COMP_TYPE:
        return "HIPDNN_ATTR_CONVOLUTION_COMP_TYPE";
    case HIPDNN_ATTR_CONVOLUTION_CONV_MODE:
        return "HIPDNN_ATTR_CONVOLUTION_CONV_MODE";
    case HIPDNN_ATTR_CONVOLUTION_DILATIONS:
        return "HIPDNN_ATTR_CONVOLUTION_DILATIONS";
    case HIPDNN_ATTR_CONVOLUTION_FILTER_STRIDES:
        return "HIPDNN_ATTR_CONVOLUTION_FILTER_STRIDES";
    case HIPDNN_ATTR_CONVOLUTION_POST_PADDINGS:
        return "HIPDNN_ATTR_CONVOLUTION_POST_PADDINGS";
    case HIPDNN_ATTR_CONVOLUTION_PRE_PADDINGS:
        return "HIPDNN_ATTR_CONVOLUTION_PRE_PADDINGS";

    // Convolution WRW operation attributes
    case HIPDNN_ATTR_OPERATION_CONVOLUTION_BWD_FILTER_X:
        return "HIPDNN_ATTR_OPERATION_CONVOLUTION_BWD_FILTER_X";
    case HIPDNN_ATTR_OPERATION_CONVOLUTION_BWD_FILTER_DY:
        return "HIPDNN_ATTR_OPERATION_CONVOLUTION_BWD_FILTER_DY";
    case HIPDNN_ATTR_OPERATION_CONVOLUTION_BWD_FILTER_DW:
        return "HIPDNN_ATTR_OPERATION_CONVOLUTION_BWD_FILTER_DW";

    // Pointwise operation attributes
    case HIPDNN_ATTR_OPERATION_POINTWISE_IN_0_EXT:
        return "HIPDNN_ATTR_OPERATION_POINTWISE_IN_0_EXT";
    case HIPDNN_ATTR_OPERATION_POINTWISE_OUT_0_EXT:
        return "HIPDNN_ATTR_OPERATION_POINTWISE_OUT_0_EXT";
    case HIPDNN_ATTR_OPERATION_POINTWISE_IN_1_EXT:
        return "HIPDNN_ATTR_OPERATION_POINTWISE_IN_1_EXT";
    case HIPDNN_ATTR_OPERATION_POINTWISE_IN_2_EXT:
        return "HIPDNN_ATTR_OPERATION_POINTWISE_IN_2_EXT";

    // Shared pointwise descriptor attributes
    case HIPDNN_ATTR_POINTWISE_MODE:
        return "HIPDNN_ATTR_POINTWISE_MODE";
    case HIPDNN_ATTR_POINTWISE_RELU_LOWER_CLIP:
        return "HIPDNN_ATTR_POINTWISE_RELU_LOWER_CLIP";
    case HIPDNN_ATTR_POINTWISE_RELU_UPPER_CLIP:
        return "HIPDNN_ATTR_POINTWISE_RELU_UPPER_CLIP";
    case HIPDNN_ATTR_POINTWISE_RELU_LOWER_CLIP_SLOPE:
        return "HIPDNN_ATTR_POINTWISE_RELU_LOWER_CLIP_SLOPE";
    case HIPDNN_ATTR_POINTWISE_SWISH_BETA:
        return "HIPDNN_ATTR_POINTWISE_SWISH_BETA";
    case HIPDNN_ATTR_POINTWISE_ELU_ALPHA:
        return "HIPDNN_ATTR_POINTWISE_ELU_ALPHA";
    case HIPDNN_ATTR_POINTWISE_SOFTPLUS_BETA:
        return "HIPDNN_ATTR_POINTWISE_SOFTPLUS_BETA";
    case HIPDNN_ATTR_POINTWISE_MATH_PREC:
        return "HIPDNN_ATTR_POINTWISE_MATH_PREC";
    case HIPDNN_ATTR_POINTWISE_AXIS:
        return "HIPDNN_ATTR_POINTWISE_AXIS";

    // Convolution backward operation attributes
    case HIPDNN_ATTR_OPERATION_CONVOLUTION_BWD_DATA_DY:
        return "HIPDNN_ATTR_OPERATION_CONVOLUTION_BWD_DATA_DY";
    case HIPDNN_ATTR_OPERATION_CONVOLUTION_BWD_DATA_W:
        return "HIPDNN_ATTR_OPERATION_CONVOLUTION_BWD_DATA_W";
    case HIPDNN_ATTR_OPERATION_CONVOLUTION_BWD_DATA_DX:
        return "HIPDNN_ATTR_OPERATION_CONVOLUTION_BWD_DATA_DX";

    // Batchnorm backward ext operation attributes
    case HIPDNN_ATTR_OPERATION_BATCHNORM_BACKWARD_DY_EXT:
        return "HIPDNN_ATTR_OPERATION_BATCHNORM_BACKWARD_DY_EXT";
    case HIPDNN_ATTR_OPERATION_BATCHNORM_BACKWARD_X_EXT:
        return "HIPDNN_ATTR_OPERATION_BATCHNORM_BACKWARD_X_EXT";
    case HIPDNN_ATTR_OPERATION_BATCHNORM_BACKWARD_SCALE_EXT:
        return "HIPDNN_ATTR_OPERATION_BATCHNORM_BACKWARD_SCALE_EXT";
    case HIPDNN_ATTR_OPERATION_BATCHNORM_BACKWARD_DX_EXT:
        return "HIPDNN_ATTR_OPERATION_BATCHNORM_BACKWARD_DX_EXT";
    case HIPDNN_ATTR_OPERATION_BATCHNORM_BACKWARD_DSCALE_EXT:
        return "HIPDNN_ATTR_OPERATION_BATCHNORM_BACKWARD_DSCALE_EXT";
    case HIPDNN_ATTR_OPERATION_BATCHNORM_BACKWARD_DBIAS_EXT:
        return "HIPDNN_ATTR_OPERATION_BATCHNORM_BACKWARD_DBIAS_EXT";
    case HIPDNN_ATTR_OPERATION_BATCHNORM_BACKWARD_MEAN_EXT:
        return "HIPDNN_ATTR_OPERATION_BATCHNORM_BACKWARD_MEAN_EXT";
    case HIPDNN_ATTR_OPERATION_BATCHNORM_BACKWARD_INV_VARIANCE_EXT:
        return "HIPDNN_ATTR_OPERATION_BATCHNORM_BACKWARD_INV_VARIANCE_EXT";
    case HIPDNN_ATTR_BATCHNORM_BACKWARD_COMP_TYPE_EXT:
        return "HIPDNN_ATTR_BATCHNORM_BACKWARD_COMP_TYPE_EXT";
    case HIPDNN_ATTR_OPERATION_BATCHNORM_BACKWARD_PEER_STATS_EXT:
        return "HIPDNN_ATTR_OPERATION_BATCHNORM_BACKWARD_PEER_STATS_EXT";

    // Batchnorm inference variance ext operation attributes
    case HIPDNN_ATTR_OPERATION_BATCHNORM_INFERENCE_VARIANCE_X_EXT:
        return "HIPDNN_ATTR_OPERATION_BATCHNORM_INFERENCE_VARIANCE_X_EXT";
    case HIPDNN_ATTR_OPERATION_BATCHNORM_INFERENCE_VARIANCE_MEAN_EXT:
        return "HIPDNN_ATTR_OPERATION_BATCHNORM_INFERENCE_VARIANCE_MEAN_EXT";
    case HIPDNN_ATTR_OPERATION_BATCHNORM_INFERENCE_VARIANCE_VARIANCE_EXT:
        return "HIPDNN_ATTR_OPERATION_BATCHNORM_INFERENCE_VARIANCE_VARIANCE_EXT";
    case HIPDNN_ATTR_OPERATION_BATCHNORM_INFERENCE_VARIANCE_SCALE_EXT:
        return "HIPDNN_ATTR_OPERATION_BATCHNORM_INFERENCE_VARIANCE_SCALE_EXT";
    case HIPDNN_ATTR_OPERATION_BATCHNORM_INFERENCE_VARIANCE_BIAS_EXT:
        return "HIPDNN_ATTR_OPERATION_BATCHNORM_INFERENCE_VARIANCE_BIAS_EXT";
    case HIPDNN_ATTR_OPERATION_BATCHNORM_INFERENCE_VARIANCE_Y_EXT:
        return "HIPDNN_ATTR_OPERATION_BATCHNORM_INFERENCE_VARIANCE_Y_EXT";
    case HIPDNN_ATTR_OPERATION_BATCHNORM_INFERENCE_VARIANCE_EPSILON_EXT:
        return "HIPDNN_ATTR_OPERATION_BATCHNORM_INFERENCE_VARIANCE_EPSILON_EXT";
    case HIPDNN_ATTR_BATCHNORM_INF_VAR_COMP_TYPE_EXT:
        return "HIPDNN_ATTR_BATCHNORM_INF_VAR_COMP_TYPE_EXT";

    // Batchnorm inference operation attributes
    case HIPDNN_ATTR_OPERATION_BATCHNORM_INFERENCE_X_EXT:
        return "HIPDNN_ATTR_OPERATION_BATCHNORM_INFERENCE_X_EXT";
    case HIPDNN_ATTR_OPERATION_BATCHNORM_INFERENCE_MEAN_EXT:
        return "HIPDNN_ATTR_OPERATION_BATCHNORM_INFERENCE_MEAN_EXT";
    case HIPDNN_ATTR_OPERATION_BATCHNORM_INFERENCE_INV_VARIANCE_EXT:
        return "HIPDNN_ATTR_OPERATION_BATCHNORM_INFERENCE_INV_VARIANCE_EXT";
    case HIPDNN_ATTR_OPERATION_BATCHNORM_INFERENCE_SCALE_EXT:
        return "HIPDNN_ATTR_OPERATION_BATCHNORM_INFERENCE_SCALE_EXT";
    case HIPDNN_ATTR_OPERATION_BATCHNORM_INFERENCE_BIAS_EXT:
        return "HIPDNN_ATTR_OPERATION_BATCHNORM_INFERENCE_BIAS_EXT";
    case HIPDNN_ATTR_OPERATION_BATCHNORM_INFERENCE_Y_EXT:
        return "HIPDNN_ATTR_OPERATION_BATCHNORM_INFERENCE_Y_EXT";
    case HIPDNN_ATTR_BATCHNORM_INF_COMP_TYPE_EXT:
        return "HIPDNN_ATTR_BATCHNORM_INF_COMP_TYPE_EXT";

    // Matmul operation attributes
    case HIPDNN_ATTR_OPERATION_MATMUL_ADESC:
        return "HIPDNN_ATTR_OPERATION_MATMUL_ADESC";
    case HIPDNN_ATTR_OPERATION_MATMUL_BDESC:
        return "HIPDNN_ATTR_OPERATION_MATMUL_BDESC";
    case HIPDNN_ATTR_OPERATION_MATMUL_CDESC:
        return "HIPDNN_ATTR_OPERATION_MATMUL_CDESC";
    case HIPDNN_ATTR_MATMUL_COMP_TYPE:
        return "HIPDNN_ATTR_MATMUL_COMP_TYPE";

    // RMSNorm operation attributes
    case HIPDNN_ATTR_OPERATION_RMSNORM_X_EXT:
        return "HIPDNN_ATTR_OPERATION_RMSNORM_X_EXT";
    case HIPDNN_ATTR_OPERATION_RMSNORM_SCALE_EXT:
        return "HIPDNN_ATTR_OPERATION_RMSNORM_SCALE_EXT";
    case HIPDNN_ATTR_OPERATION_RMSNORM_EPSILON_EXT:
        return "HIPDNN_ATTR_OPERATION_RMSNORM_EPSILON_EXT";
    case HIPDNN_ATTR_OPERATION_RMSNORM_Y_EXT:
        return "HIPDNN_ATTR_OPERATION_RMSNORM_Y_EXT";
    case HIPDNN_ATTR_OPERATION_RMSNORM_BIAS_EXT:
        return "HIPDNN_ATTR_OPERATION_RMSNORM_BIAS_EXT";
    case HIPDNN_ATTR_OPERATION_RMSNORM_INV_RMS_EXT:
        return "HIPDNN_ATTR_OPERATION_RMSNORM_INV_RMS_EXT";
    case HIPDNN_ATTR_OPERATION_RMSNORM_FWD_PHASE_EXT:
        return "HIPDNN_ATTR_OPERATION_RMSNORM_FWD_PHASE_EXT";
    case HIPDNN_ATTR_RMSNORM_COMP_TYPE_EXT:
        return "HIPDNN_ATTR_RMSNORM_COMP_TYPE_EXT";

    // SDPA fprop operation attributes
    case HIPDNN_ATTR_OPERATION_SDPA_FWD_QDESC:
        return "HIPDNN_ATTR_OPERATION_SDPA_FWD_QDESC";
    case HIPDNN_ATTR_OPERATION_SDPA_FWD_KDESC:
        return "HIPDNN_ATTR_OPERATION_SDPA_FWD_KDESC";
    case HIPDNN_ATTR_OPERATION_SDPA_FWD_VDESC:
        return "HIPDNN_ATTR_OPERATION_SDPA_FWD_VDESC";
    case HIPDNN_ATTR_OPERATION_SDPA_FWD_ODESC:
        return "HIPDNN_ATTR_OPERATION_SDPA_FWD_ODESC";
    case HIPDNN_ATTR_OPERATION_SDPA_FWD_ATTN_MASK_EXT:
        return "HIPDNN_ATTR_OPERATION_SDPA_FWD_ATTN_MASK_EXT";
    case HIPDNN_ATTR_OPERATION_SDPA_FWD_SCALEDESC:
        return "HIPDNN_ATTR_OPERATION_SDPA_FWD_SCALEDESC";
    case HIPDNN_ATTR_OPERATION_SDPA_FWD_SEQ_LEN_QDESC:
        return "HIPDNN_ATTR_OPERATION_SDPA_FWD_SEQ_LEN_QDESC";
    case HIPDNN_ATTR_OPERATION_SDPA_FWD_SEQ_LEN_KVDESC:
        return "HIPDNN_ATTR_OPERATION_SDPA_FWD_SEQ_LEN_KVDESC";
    case HIPDNN_ATTR_OPERATION_SDPA_FWD_SEED_EXT:
        return "HIPDNN_ATTR_OPERATION_SDPA_FWD_SEED_EXT";
    case HIPDNN_ATTR_OPERATION_SDPA_FWD_OFFSET_EXT:
        return "HIPDNN_ATTR_OPERATION_SDPA_FWD_OFFSET_EXT";
    case HIPDNN_ATTR_OPERATION_SDPA_FWD_DROPOUT_MASK_EXT:
        return "HIPDNN_ATTR_OPERATION_SDPA_FWD_DROPOUT_MASK_EXT";
    case HIPDNN_ATTR_OPERATION_SDPA_FWD_DROPOUT_SCALE_EXT:
        return "HIPDNN_ATTR_OPERATION_SDPA_FWD_DROPOUT_SCALE_EXT";
    case HIPDNN_ATTR_OPERATION_SDPA_FWD_PAGE_TABLE_KDESC:
        return "HIPDNN_ATTR_OPERATION_SDPA_FWD_PAGE_TABLE_KDESC";
    case HIPDNN_ATTR_OPERATION_SDPA_FWD_PAGE_TABLE_VDESC:
        return "HIPDNN_ATTR_OPERATION_SDPA_FWD_PAGE_TABLE_VDESC";
    case HIPDNN_ATTR_OPERATION_SDPA_FWD_BLOCK_MASK_DESC:
        return "HIPDNN_ATTR_OPERATION_SDPA_FWD_BLOCK_MASK_DESC";
    case HIPDNN_ATTR_OPERATION_SDPA_FWD_SINK_TOKEN_EXT:
        return "HIPDNN_ATTR_OPERATION_SDPA_FWD_SINK_TOKEN_EXT";
    case HIPDNN_ATTR_OPERATION_SDPA_FWD_DESCALE_Q_EXT:
        return "HIPDNN_ATTR_OPERATION_SDPA_FWD_DESCALE_Q_EXT";
    case HIPDNN_ATTR_OPERATION_SDPA_FWD_DESCALE_K_EXT:
        return "HIPDNN_ATTR_OPERATION_SDPA_FWD_DESCALE_K_EXT";
    case HIPDNN_ATTR_OPERATION_SDPA_FWD_DESCALE_V_EXT:
        return "HIPDNN_ATTR_OPERATION_SDPA_FWD_DESCALE_V_EXT";
    case HIPDNN_ATTR_OPERATION_SDPA_FWD_DESCALE_S_EXT:
        return "HIPDNN_ATTR_OPERATION_SDPA_FWD_DESCALE_S_EXT";
    case HIPDNN_ATTR_OPERATION_SDPA_FWD_SCALE_S_EXT:
        return "HIPDNN_ATTR_OPERATION_SDPA_FWD_SCALE_S_EXT";
    case HIPDNN_ATTR_OPERATION_SDPA_FWD_SCALE_O_EXT:
        return "HIPDNN_ATTR_OPERATION_SDPA_FWD_SCALE_O_EXT";
    case HIPDNN_ATTR_OPERATION_SDPA_FWD_STATSDESC:
        return "HIPDNN_ATTR_OPERATION_SDPA_FWD_STATSDESC";
    case HIPDNN_ATTR_OPERATION_SDPA_FWD_MAX_EXT:
        return "HIPDNN_ATTR_OPERATION_SDPA_FWD_MAX_EXT";
    case HIPDNN_ATTR_OPERATION_SDPA_FWD_SUM_EXP_EXT:
        return "HIPDNN_ATTR_OPERATION_SDPA_FWD_SUM_EXP_EXT";
    case HIPDNN_ATTR_OPERATION_SDPA_FWD_RNG_DUMP_EXT:
        return "HIPDNN_ATTR_OPERATION_SDPA_FWD_RNG_DUMP_EXT";
    case HIPDNN_ATTR_OPERATION_SDPA_FWD_AMAX_S_EXT:
        return "HIPDNN_ATTR_OPERATION_SDPA_FWD_AMAX_S_EXT";
    case HIPDNN_ATTR_OPERATION_SDPA_FWD_AMAX_O_EXT:
        return "HIPDNN_ATTR_OPERATION_SDPA_FWD_AMAX_O_EXT";
    case HIPDNN_ATTR_SDPA_FWD_GENERATE_STATS_EXT:
        return "HIPDNN_ATTR_SDPA_FWD_GENERATE_STATS_EXT";
    case HIPDNN_ATTR_SDPA_FWD_ALIBI_MASK_EXT:
        return "HIPDNN_ATTR_SDPA_FWD_ALIBI_MASK_EXT";
    case HIPDNN_ATTR_SDPA_FWD_PADDING_MASK_EXT:
        return "HIPDNN_ATTR_SDPA_FWD_PADDING_MASK_EXT";
    case HIPDNN_ATTR_SDPA_FWD_CAUSAL_MASK_EXT:
        return "HIPDNN_ATTR_SDPA_FWD_CAUSAL_MASK_EXT";
    case HIPDNN_ATTR_SDPA_FWD_CAUSAL_MASK_BOTTOM_RIGHT_EXT:
        return "HIPDNN_ATTR_SDPA_FWD_CAUSAL_MASK_BOTTOM_RIGHT_EXT";
    case HIPDNN_ATTR_SDPA_FWD_DROPOUT_PROBABILITY_EXT:
        return "HIPDNN_ATTR_SDPA_FWD_DROPOUT_PROBABILITY_EXT";
    case HIPDNN_ATTR_SDPA_FWD_ATTN_SCALE_VALUE_EXT:
        return "HIPDNN_ATTR_SDPA_FWD_ATTN_SCALE_VALUE_EXT";
    case HIPDNN_ATTR_SDPA_FWD_LEFT_BOUND_EXT:
        return "HIPDNN_ATTR_SDPA_FWD_LEFT_BOUND_EXT";
    case HIPDNN_ATTR_SDPA_FWD_RIGHT_BOUND_EXT:
        return "HIPDNN_ATTR_SDPA_FWD_RIGHT_BOUND_EXT";
    case HIPDNN_ATTR_SDPA_FWD_MAX_SEQ_LEN_KV_EXT:
        return "HIPDNN_ATTR_SDPA_FWD_MAX_SEQ_LEN_KV_EXT";
    case HIPDNN_ATTR_SDPA_FWD_DIAGONAL_ALIGNMENT_EXT:
        return "HIPDNN_ATTR_SDPA_FWD_DIAGONAL_ALIGNMENT_EXT";
    case HIPDNN_ATTR_SDPA_FWD_MMA_CORE_MODE_EXT:
        return "HIPDNN_ATTR_SDPA_FWD_MMA_CORE_MODE_EXT";
    case HIPDNN_ATTR_SDPA_FWD_IMPLEMENTATION_EXT:
        return "HIPDNN_ATTR_SDPA_FWD_IMPLEMENTATION_EXT";
    case HIPDNN_ATTR_SDPA_FWD_COMP_TYPE_EXT:
        return "HIPDNN_ATTR_SDPA_FWD_COMP_TYPE_EXT";

    // Layernorm operation attributes
    case HIPDNN_ATTR_OPERATION_LAYERNORM_X_EXT:
        return "HIPDNN_ATTR_OPERATION_LAYERNORM_X_EXT";
    case HIPDNN_ATTR_OPERATION_LAYERNORM_SCALE_EXT:
        return "HIPDNN_ATTR_OPERATION_LAYERNORM_SCALE_EXT";
    case HIPDNN_ATTR_OPERATION_LAYERNORM_BIAS_EXT:
        return "HIPDNN_ATTR_OPERATION_LAYERNORM_BIAS_EXT";
    case HIPDNN_ATTR_OPERATION_LAYERNORM_EPSILON_EXT:
        return "HIPDNN_ATTR_OPERATION_LAYERNORM_EPSILON_EXT";
    case HIPDNN_ATTR_OPERATION_LAYERNORM_Y_EXT:
        return "HIPDNN_ATTR_OPERATION_LAYERNORM_Y_EXT";
    case HIPDNN_ATTR_OPERATION_LAYERNORM_MEAN_EXT:
        return "HIPDNN_ATTR_OPERATION_LAYERNORM_MEAN_EXT";
    case HIPDNN_ATTR_OPERATION_LAYERNORM_INV_VARIANCE_EXT:
        return "HIPDNN_ATTR_OPERATION_LAYERNORM_INV_VARIANCE_EXT";
    case HIPDNN_ATTR_OPERATION_LAYERNORM_FWD_PHASE_EXT:
        return "HIPDNN_ATTR_OPERATION_LAYERNORM_FWD_PHASE_EXT";
    case HIPDNN_ATTR_LAYERNORM_COMP_TYPE_EXT:
        return "HIPDNN_ATTR_LAYERNORM_COMP_TYPE_EXT";
    case HIPDNN_ATTR_OPERATION_LAYERNORM_NORMALIZED_DIM_COUNT_EXT:
        return "HIPDNN_ATTR_OPERATION_LAYERNORM_NORMALIZED_DIM_COUNT_EXT";

    // Block scale quantize operation attributes
    case HIPDNN_ATTR_OPERATION_BLOCK_SCALE_QUANTIZE_XDESC:
        return "HIPDNN_ATTR_OPERATION_BLOCK_SCALE_QUANTIZE_XDESC";
    case HIPDNN_ATTR_OPERATION_BLOCK_SCALE_QUANTIZE_YDESC:
        return "HIPDNN_ATTR_OPERATION_BLOCK_SCALE_QUANTIZE_YDESC";
    case HIPDNN_ATTR_OPERATION_BLOCK_SCALE_QUANTIZE_SCALE_DESC:
        return "HIPDNN_ATTR_OPERATION_BLOCK_SCALE_QUANTIZE_SCALE_DESC";
    case HIPDNN_ATTR_OPERATION_BLOCK_SCALE_QUANTIZE_BLOCK_SIZE:
        return "HIPDNN_ATTR_OPERATION_BLOCK_SCALE_QUANTIZE_BLOCK_SIZE";
    case HIPDNN_ATTR_OPERATION_BLOCK_SCALE_QUANTIZE_AXIS_EXT:
        return "HIPDNN_ATTR_OPERATION_BLOCK_SCALE_QUANTIZE_AXIS_EXT";
    case HIPDNN_ATTR_OPERATION_BLOCK_SCALE_QUANTIZE_TRANSPOSE_EXT:
        return "HIPDNN_ATTR_OPERATION_BLOCK_SCALE_QUANTIZE_TRANSPOSE_EXT";
    case HIPDNN_ATTR_OPERATION_BLOCK_SCALE_QUANTIZE_MATH_PREC:
        return "HIPDNN_ATTR_OPERATION_BLOCK_SCALE_QUANTIZE_MATH_PREC";

    // Batchnorm training forward operation attributes
    case HIPDNN_ATTR_OPERATION_BATCHNORM_X_EXT:
        return "HIPDNN_ATTR_OPERATION_BATCHNORM_X_EXT";
    case HIPDNN_ATTR_OPERATION_BATCHNORM_SCALE_EXT:
        return "HIPDNN_ATTR_OPERATION_BATCHNORM_SCALE_EXT";
    case HIPDNN_ATTR_OPERATION_BATCHNORM_BIAS_EXT:
        return "HIPDNN_ATTR_OPERATION_BATCHNORM_BIAS_EXT";
    case HIPDNN_ATTR_OPERATION_BATCHNORM_EPSILON_EXT:
        return "HIPDNN_ATTR_OPERATION_BATCHNORM_EPSILON_EXT";
    case HIPDNN_ATTR_OPERATION_BATCHNORM_Y_EXT:
        return "HIPDNN_ATTR_OPERATION_BATCHNORM_Y_EXT";
    case HIPDNN_ATTR_OPERATION_BATCHNORM_PREV_RUNNING_MEAN_EXT:
        return "HIPDNN_ATTR_OPERATION_BATCHNORM_PREV_RUNNING_MEAN_EXT";
    case HIPDNN_ATTR_OPERATION_BATCHNORM_PREV_RUNNING_VARIANCE_EXT:
        return "HIPDNN_ATTR_OPERATION_BATCHNORM_PREV_RUNNING_VARIANCE_EXT";
    case HIPDNN_ATTR_OPERATION_BATCHNORM_MOMENTUM_EXT:
        return "HIPDNN_ATTR_OPERATION_BATCHNORM_MOMENTUM_EXT";
    case HIPDNN_ATTR_OPERATION_BATCHNORM_MEAN_EXT:
        return "HIPDNN_ATTR_OPERATION_BATCHNORM_MEAN_EXT";
    case HIPDNN_ATTR_OPERATION_BATCHNORM_INV_VARIANCE_EXT:
        return "HIPDNN_ATTR_OPERATION_BATCHNORM_INV_VARIANCE_EXT";
    case HIPDNN_ATTR_OPERATION_BATCHNORM_NEXT_RUNNING_MEAN_EXT:
        return "HIPDNN_ATTR_OPERATION_BATCHNORM_NEXT_RUNNING_MEAN_EXT";
    case HIPDNN_ATTR_OPERATION_BATCHNORM_NEXT_RUNNING_VARIANCE_EXT:
        return "HIPDNN_ATTR_OPERATION_BATCHNORM_NEXT_RUNNING_VARIANCE_EXT";
    case HIPDNN_ATTR_BATCHNORM_COMP_TYPE_EXT:
        return "HIPDNN_ATTR_BATCHNORM_COMP_TYPE_EXT";
    case HIPDNN_ATTR_OPERATION_BATCHNORM_PEER_STATS_EXT:
        return "HIPDNN_ATTR_OPERATION_BATCHNORM_PEER_STATS_EXT";

    // SDPA bprop operation attributes
    case HIPDNN_ATTR_OPERATION_SDPA_BWD_Q_EXT:
        return "HIPDNN_ATTR_OPERATION_SDPA_BWD_Q_EXT";
    case HIPDNN_ATTR_OPERATION_SDPA_BWD_K_EXT:
        return "HIPDNN_ATTR_OPERATION_SDPA_BWD_K_EXT";
    case HIPDNN_ATTR_OPERATION_SDPA_BWD_V_EXT:
        return "HIPDNN_ATTR_OPERATION_SDPA_BWD_V_EXT";
    case HIPDNN_ATTR_OPERATION_SDPA_BWD_O_EXT:
        return "HIPDNN_ATTR_OPERATION_SDPA_BWD_O_EXT";
    case HIPDNN_ATTR_OPERATION_SDPA_BWD_DO_EXT:
        return "HIPDNN_ATTR_OPERATION_SDPA_BWD_DO_EXT";
    case HIPDNN_ATTR_OPERATION_SDPA_BWD_STATS_EXT:
        return "HIPDNN_ATTR_OPERATION_SDPA_BWD_STATS_EXT";
    case HIPDNN_ATTR_OPERATION_SDPA_BWD_DQ_EXT:
        return "HIPDNN_ATTR_OPERATION_SDPA_BWD_DQ_EXT";
    case HIPDNN_ATTR_OPERATION_SDPA_BWD_DK_EXT:
        return "HIPDNN_ATTR_OPERATION_SDPA_BWD_DK_EXT";
    case HIPDNN_ATTR_OPERATION_SDPA_BWD_DV_EXT:
        return "HIPDNN_ATTR_OPERATION_SDPA_BWD_DV_EXT";
    case HIPDNN_ATTR_OPERATION_SDPA_BWD_SCALE_EXT:
        return "HIPDNN_ATTR_OPERATION_SDPA_BWD_SCALE_EXT";
    case HIPDNN_ATTR_OPERATION_SDPA_BWD_ATTN_MASK_EXT:
        return "HIPDNN_ATTR_OPERATION_SDPA_BWD_ATTN_MASK_EXT";
    case HIPDNN_ATTR_OPERATION_SDPA_BWD_SEQ_LEN_Q_EXT:
        return "HIPDNN_ATTR_OPERATION_SDPA_BWD_SEQ_LEN_Q_EXT";
    case HIPDNN_ATTR_OPERATION_SDPA_BWD_SEQ_LEN_KV_EXT:
        return "HIPDNN_ATTR_OPERATION_SDPA_BWD_SEQ_LEN_KV_EXT";
    case HIPDNN_ATTR_OPERATION_SDPA_BWD_SEED_EXT:
        return "HIPDNN_ATTR_OPERATION_SDPA_BWD_SEED_EXT";
    case HIPDNN_ATTR_OPERATION_SDPA_BWD_OFFSET_EXT:
        return "HIPDNN_ATTR_OPERATION_SDPA_BWD_OFFSET_EXT";
    case HIPDNN_ATTR_OPERATION_SDPA_BWD_DROPOUT_MASK_EXT:
        return "HIPDNN_ATTR_OPERATION_SDPA_BWD_DROPOUT_MASK_EXT";
    case HIPDNN_ATTR_OPERATION_SDPA_BWD_DROPOUT_SCALE_EXT:
        return "HIPDNN_ATTR_OPERATION_SDPA_BWD_DROPOUT_SCALE_EXT";
    case HIPDNN_ATTR_OPERATION_SDPA_BWD_DROPOUT_SCALE_INV_EXT:
        return "HIPDNN_ATTR_OPERATION_SDPA_BWD_DROPOUT_SCALE_INV_EXT";
    case HIPDNN_ATTR_OPERATION_SDPA_BWD_DBIAS_EXT:
        return "HIPDNN_ATTR_OPERATION_SDPA_BWD_DBIAS_EXT";
    case HIPDNN_ATTR_SDPA_BWD_ALIBI_MASK_EXT:
        return "HIPDNN_ATTR_SDPA_BWD_ALIBI_MASK_EXT";
    case HIPDNN_ATTR_SDPA_BWD_PADDING_MASK_EXT:
        return "HIPDNN_ATTR_SDPA_BWD_PADDING_MASK_EXT";
    case HIPDNN_ATTR_SDPA_BWD_CAUSAL_MASK_EXT:
        return "HIPDNN_ATTR_SDPA_BWD_CAUSAL_MASK_EXT";
    case HIPDNN_ATTR_SDPA_BWD_CAUSAL_MASK_BOTTOM_RIGHT_EXT:
        return "HIPDNN_ATTR_SDPA_BWD_CAUSAL_MASK_BOTTOM_RIGHT_EXT";
    case HIPDNN_ATTR_SDPA_BWD_DROPOUT_PROBABILITY_EXT:
        return "HIPDNN_ATTR_SDPA_BWD_DROPOUT_PROBABILITY_EXT";
    case HIPDNN_ATTR_SDPA_BWD_ATTN_SCALE_VALUE_EXT:
        return "HIPDNN_ATTR_SDPA_BWD_ATTN_SCALE_VALUE_EXT";
    case HIPDNN_ATTR_SDPA_BWD_LEFT_BOUND_EXT:
        return "HIPDNN_ATTR_SDPA_BWD_LEFT_BOUND_EXT";
    case HIPDNN_ATTR_SDPA_BWD_RIGHT_BOUND_EXT:
        return "HIPDNN_ATTR_SDPA_BWD_RIGHT_BOUND_EXT";
    case HIPDNN_ATTR_SDPA_BWD_DIAGONAL_ALIGNMENT_EXT:
        return "HIPDNN_ATTR_SDPA_BWD_DIAGONAL_ALIGNMENT_EXT";
    case HIPDNN_ATTR_SDPA_BWD_COMP_TYPE_EXT:
        return "HIPDNN_ATTR_SDPA_BWD_COMP_TYPE_EXT";

    // Block scale dequantize operation attributes
    case HIPDNN_ATTR_OPERATION_BLOCK_SCALE_DEQUANTIZE_XDESC:
        return "HIPDNN_ATTR_OPERATION_BLOCK_SCALE_DEQUANTIZE_XDESC";
    case HIPDNN_ATTR_OPERATION_BLOCK_SCALE_DEQUANTIZE_SCALE_DESC:
        return "HIPDNN_ATTR_OPERATION_BLOCK_SCALE_DEQUANTIZE_SCALE_DESC";
    case HIPDNN_ATTR_OPERATION_BLOCK_SCALE_DEQUANTIZE_YDESC:
        return "HIPDNN_ATTR_OPERATION_BLOCK_SCALE_DEQUANTIZE_YDESC";
    case HIPDNN_ATTR_OPERATION_BLOCK_SCALE_DEQUANTIZE_BLOCK_SIZE:
        return "HIPDNN_ATTR_OPERATION_BLOCK_SCALE_DEQUANTIZE_BLOCK_SIZE";
    case HIPDNN_ATTR_OPERATION_BLOCK_SCALE_DEQUANTIZE_NEG_SCALE:
        return "HIPDNN_ATTR_OPERATION_BLOCK_SCALE_DEQUANTIZE_NEG_SCALE";
    case HIPDNN_ATTR_OPERATION_BLOCK_SCALE_DEQUANTIZE_MATH_PREC:
        return "HIPDNN_ATTR_OPERATION_BLOCK_SCALE_DEQUANTIZE_MATH_PREC";

    // Resample forward operation attributes
    case HIPDNN_ATTR_OPERATION_RESAMPLE_FWD_XDESC:
        return "HIPDNN_ATTR_OPERATION_RESAMPLE_FWD_XDESC";
    case HIPDNN_ATTR_OPERATION_RESAMPLE_FWD_YDESC:
        return "HIPDNN_ATTR_OPERATION_RESAMPLE_FWD_YDESC";
    case HIPDNN_ATTR_OPERATION_RESAMPLE_FWD_IDXDESC:
        return "HIPDNN_ATTR_OPERATION_RESAMPLE_FWD_IDXDESC";
    case HIPDNN_ATTR_RESAMPLE_MODE:
        return "HIPDNN_ATTR_RESAMPLE_MODE";
    case HIPDNN_ATTR_RESAMPLE_PRE_PADDINGS:
        return "HIPDNN_ATTR_RESAMPLE_PRE_PADDINGS";
    case HIPDNN_ATTR_RESAMPLE_POST_PADDINGS:
        return "HIPDNN_ATTR_RESAMPLE_POST_PADDINGS";
    case HIPDNN_ATTR_RESAMPLE_STRIDES:
        return "HIPDNN_ATTR_RESAMPLE_STRIDES";
    case HIPDNN_ATTR_RESAMPLE_WINDOW_DIMS:
        return "HIPDNN_ATTR_RESAMPLE_WINDOW_DIMS";
    case HIPDNN_ATTR_RESAMPLE_PADDING_MODE:
        return "HIPDNN_ATTR_RESAMPLE_PADDING_MODE";
    case HIPDNN_ATTR_RESAMPLE_GENERATE_INDEX_EXT:
        return "HIPDNN_ATTR_RESAMPLE_GENERATE_INDEX_EXT";
    case HIPDNN_ATTR_RESAMPLE_COMP_TYPE:
        return "HIPDNN_ATTR_RESAMPLE_COMP_TYPE";

    // Custom op operation attributes
    case HIPDNN_ATTR_OPERATION_CUSTOM_OP_INPUTS_EXT:
        return "HIPDNN_ATTR_OPERATION_CUSTOM_OP_INPUTS_EXT";
    case HIPDNN_ATTR_OPERATION_CUSTOM_OP_OUTPUTS_EXT:
        return "HIPDNN_ATTR_OPERATION_CUSTOM_OP_OUTPUTS_EXT";
    case HIPDNN_ATTR_OPERATION_CUSTOM_OP_ID_EXT:
        return "HIPDNN_ATTR_OPERATION_CUSTOM_OP_ID_EXT";
    case HIPDNN_ATTR_OPERATION_CUSTOM_OP_DATA_EXT:
        return "HIPDNN_ATTR_OPERATION_CUSTOM_OP_DATA_EXT";
    case HIPDNN_ATTR_CUSTOM_OP_COMP_TYPE_EXT:
        return "HIPDNN_ATTR_CUSTOM_OP_COMP_TYPE_EXT";

    // Reduction operation attributes
    case HIPDNN_ATTR_OPERATION_REDUCTION_XDESC:
        return "HIPDNN_ATTR_OPERATION_REDUCTION_XDESC";
    case HIPDNN_ATTR_OPERATION_REDUCTION_YDESC:
        return "HIPDNN_ATTR_OPERATION_REDUCTION_YDESC";
    case HIPDNN_ATTR_REDUCTION_OPERATOR:
        return "HIPDNN_ATTR_REDUCTION_OPERATOR";
    case HIPDNN_ATTR_REDUCTION_COMP_TYPE:
        return "HIPDNN_ATTR_REDUCTION_COMP_TYPE";
    case HIPDNN_ATTR_REDUCTION_IS_DETERMINISTIC:
        return "HIPDNN_ATTR_REDUCTION_IS_DETERMINISTIC";

    // RMSNorm backward operation attributes
    case HIPDNN_ATTR_OPERATION_RMSNORM_BACKWARD_DY_EXT:
        return "HIPDNN_ATTR_OPERATION_RMSNORM_BACKWARD_DY_EXT";
    case HIPDNN_ATTR_OPERATION_RMSNORM_BACKWARD_X_EXT:
        return "HIPDNN_ATTR_OPERATION_RMSNORM_BACKWARD_X_EXT";
    case HIPDNN_ATTR_OPERATION_RMSNORM_BACKWARD_SCALE_EXT:
        return "HIPDNN_ATTR_OPERATION_RMSNORM_BACKWARD_SCALE_EXT";
    case HIPDNN_ATTR_OPERATION_RMSNORM_BACKWARD_INV_RMS_EXT:
        return "HIPDNN_ATTR_OPERATION_RMSNORM_BACKWARD_INV_RMS_EXT";
    case HIPDNN_ATTR_OPERATION_RMSNORM_BACKWARD_DX_EXT:
        return "HIPDNN_ATTR_OPERATION_RMSNORM_BACKWARD_DX_EXT";
    case HIPDNN_ATTR_OPERATION_RMSNORM_BACKWARD_DSCALE_EXT:
        return "HIPDNN_ATTR_OPERATION_RMSNORM_BACKWARD_DSCALE_EXT";
    case HIPDNN_ATTR_OPERATION_RMSNORM_BACKWARD_DBIAS_EXT:
        return "HIPDNN_ATTR_OPERATION_RMSNORM_BACKWARD_DBIAS_EXT";
    case HIPDNN_ATTR_RMSNORM_BACKWARD_COMP_TYPE_EXT:
        return "HIPDNN_ATTR_RMSNORM_BACKWARD_COMP_TYPE_EXT";

    // Operation extension attributes
    case HIPDNN_ATTR_OPERATION_NAME_EXT:
        return "HIPDNN_ATTR_OPERATION_NAME_EXT";
    case HIPDNN_ATTR_OPERATION_TYPE_EXT:
        return "HIPDNN_ATTR_OPERATION_TYPE_EXT";

    // Extension API
    case HIPDNN_ATTR_KNOB_INFO_SERIALIZED_VALUE:
        return "HIPDNN_ATTR_KNOB_INFO_SERIALIZED_VALUE";
    case HIPDNN_ATTR_KNOB_CHOICE_SERIALIZED_VALUE:
        return "HIPDNN_ATTR_KNOB_CHOICE_SERIALIZED_VALUE";

    default:
        return "HIPDNN_ATTR_UNKNOWN";
    }
}

inline const char* hipdnnGetOperationTypeString(hipdnnOperationType_ext_t type)
{
    switch(type)
    {
    case HIPDNN_OPERATION_TYPE_BATCHNORM_EXT:
        return "HIPDNN_OPERATION_TYPE_BATCHNORM_EXT";
    case HIPDNN_OPERATION_TYPE_BATCHNORM_BACKWARD_EXT:
        return "HIPDNN_OPERATION_TYPE_BATCHNORM_BACKWARD_EXT";
    case HIPDNN_OPERATION_TYPE_BATCHNORM_INFERENCE_EXT:
        return "HIPDNN_OPERATION_TYPE_BATCHNORM_INFERENCE_EXT";
    case HIPDNN_OPERATION_TYPE_BATCHNORM_INFERENCE_VARIANCE_EXT:
        return "HIPDNN_OPERATION_TYPE_BATCHNORM_INFERENCE_VARIANCE_EXT";
    case HIPDNN_OPERATION_TYPE_BLOCK_SCALE_DEQUANTIZE_EXT:
        return "HIPDNN_OPERATION_TYPE_BLOCK_SCALE_DEQUANTIZE_EXT";
    case HIPDNN_OPERATION_TYPE_BLOCK_SCALE_QUANTIZE_EXT:
        return "HIPDNN_OPERATION_TYPE_BLOCK_SCALE_QUANTIZE_EXT";
    case HIPDNN_OPERATION_TYPE_CONVOLUTION_BACKWARD_DATA_EXT:
        return "HIPDNN_OPERATION_TYPE_CONVOLUTION_BACKWARD_DATA_EXT";
    case HIPDNN_OPERATION_TYPE_CONVOLUTION_BACKWARD_WEIGHTS_EXT:
        return "HIPDNN_OPERATION_TYPE_CONVOLUTION_BACKWARD_WEIGHTS_EXT";
    case HIPDNN_OPERATION_TYPE_CONVOLUTION_FORWARD_EXT:
        return "HIPDNN_OPERATION_TYPE_CONVOLUTION_FORWARD_EXT";
    case HIPDNN_OPERATION_TYPE_CUSTOM_OP_EXT:
        return "HIPDNN_OPERATION_TYPE_CUSTOM_OP_EXT";
    case HIPDNN_OPERATION_TYPE_LAYERNORM_EXT:
        return "HIPDNN_OPERATION_TYPE_LAYERNORM_EXT";
    case HIPDNN_OPERATION_TYPE_MATMUL_EXT:
        return "HIPDNN_OPERATION_TYPE_MATMUL_EXT";
    case HIPDNN_OPERATION_TYPE_NOT_SET_EXT:
        return "HIPDNN_OPERATION_TYPE_NOT_SET_EXT";
    case HIPDNN_OPERATION_TYPE_POINTWISE_EXT:
        return "HIPDNN_OPERATION_TYPE_POINTWISE_EXT";
    case HIPDNN_OPERATION_TYPE_RESAMPLE_FWD:
        return "HIPDNN_OPERATION_TYPE_RESAMPLE_FWD";
    case HIPDNN_OPERATION_TYPE_REDUCTION_EXT:
        return "HIPDNN_OPERATION_TYPE_REDUCTION_EXT";
    case HIPDNN_OPERATION_TYPE_RMSNORM_EXT:
        return "HIPDNN_OPERATION_TYPE_RMSNORM_EXT";
    case HIPDNN_OPERATION_TYPE_RMSNORM_BACKWARD_EXT:
        return "HIPDNN_OPERATION_TYPE_RMSNORM_BACKWARD_EXT";
    case HIPDNN_OPERATION_TYPE_SDPA_BACKWARD_EXT:
        return "HIPDNN_OPERATION_TYPE_SDPA_BACKWARD_EXT";
    case HIPDNN_OPERATION_TYPE_SDPA_FORWARD_EXT:
        return "HIPDNN_OPERATION_TYPE_SDPA_FORWARD_EXT";
    default:
        return "HIPDNN_OPERATION_TYPE_UNKNOWN";
    }
}

inline const char* hipdnnGetPluginLoadingModeString(hipdnnPluginLoadingMode_ext_t mode)
{
    switch(mode)
    {
    case HIPDNN_PLUGIN_LOADING_ADDITIVE:
        return "HIPDNN_PLUGIN_LOADING_ADDITIVE";
    case HIPDNN_PLUGIN_LOADING_ABSOLUTE:
        return "HIPDNN_PLUGIN_LOADING_ABSOLUTE";
    default:
        return "HIPDNN_PLUGIN_LOADING_UNKNOWN";
    }
}

inline const char* hipdnnGetPluginUnloadingModeString(hipdnnPluginUnloadingMode_ext_t mode)
{
    switch(mode)
    {
    case HIPDNN_PLUGIN_UNLOAD_LAZY:
        return "HIPDNN_PLUGIN_UNLOAD_LAZY";
    case HIPDNN_PLUGIN_UNLOAD_EAGER:
        return "HIPDNN_PLUGIN_UNLOAD_EAGER";
    default:
        return "HIPDNN_PLUGIN_UNLOAD_UNKNOWN";
    }
}

inline const char* hipdnnGetNormFwdPhaseString(hipdnnNormFwdPhase_t phase)
{
    switch(phase)
    {
    case HIPDNN_NORM_FWD_INFERENCE:
        return "HIPDNN_NORM_FWD_INFERENCE";
    case HIPDNN_NORM_FWD_TRAINING:
        return "HIPDNN_NORM_FWD_TRAINING";
    default:
        return "HIPDNN_NORM_FWD_UNKNOWN";
    }
}

inline const char* hipdnnGetConvolutionModeString(hipdnnConvolutionMode_t mode)
{
    switch(mode)
    {
    case HIPDNN_CONVOLUTION:
        return "HIPDNN_CONVOLUTION";
    case HIPDNN_CROSS_CORRELATION:
        return "HIPDNN_CROSS_CORRELATION";
    default:
        return "HIPDNN_CONVOLUTION_UNKNOWN";
    }
}

inline const char* hipdnnGetPointwiseModeString(hipdnnPointwiseMode_t mode)
{
    switch(mode)
    {
    case HIPDNN_POINTWISE_ABS:
        return "HIPDNN_POINTWISE_ABS";
    case HIPDNN_POINTWISE_ADD:
        return "HIPDNN_POINTWISE_ADD";
    case HIPDNN_POINTWISE_ADD_SQUARE:
        return "HIPDNN_POINTWISE_ADD_SQUARE";
    case HIPDNN_POINTWISE_BINARY_SELECT:
        return "HIPDNN_POINTWISE_BINARY_SELECT";
    case HIPDNN_POINTWISE_CEIL:
        return "HIPDNN_POINTWISE_CEIL";
    case HIPDNN_POINTWISE_CMP_EQ:
        return "HIPDNN_POINTWISE_CMP_EQ";
    case HIPDNN_POINTWISE_CMP_GE:
        return "HIPDNN_POINTWISE_CMP_GE";
    case HIPDNN_POINTWISE_CMP_GT:
        return "HIPDNN_POINTWISE_CMP_GT";
    case HIPDNN_POINTWISE_CMP_LE:
        return "HIPDNN_POINTWISE_CMP_LE";
    case HIPDNN_POINTWISE_CMP_LT:
        return "HIPDNN_POINTWISE_CMP_LT";
    case HIPDNN_POINTWISE_CMP_NEQ:
        return "HIPDNN_POINTWISE_CMP_NEQ";
    case HIPDNN_POINTWISE_DIV:
        return "HIPDNN_POINTWISE_DIV";
    case HIPDNN_POINTWISE_ELU_BWD:
        return "HIPDNN_POINTWISE_ELU_BWD";
    case HIPDNN_POINTWISE_ELU_FWD:
        return "HIPDNN_POINTWISE_ELU_FWD";
    case HIPDNN_POINTWISE_ERF:
        return "HIPDNN_POINTWISE_ERF";
    case HIPDNN_POINTWISE_EXP:
        return "HIPDNN_POINTWISE_EXP";
    case HIPDNN_POINTWISE_FLOOR:
        return "HIPDNN_POINTWISE_FLOOR";
    case HIPDNN_POINTWISE_GELU_APPROX_TANH_BWD:
        return "HIPDNN_POINTWISE_GELU_APPROX_TANH_BWD";
    case HIPDNN_POINTWISE_GELU_APPROX_TANH_FWD:
        return "HIPDNN_POINTWISE_GELU_APPROX_TANH_FWD";
    case HIPDNN_POINTWISE_GELU_BWD:
        return "HIPDNN_POINTWISE_GELU_BWD";
    case HIPDNN_POINTWISE_GELU_FWD:
        return "HIPDNN_POINTWISE_GELU_FWD";
    case HIPDNN_POINTWISE_GEN_INDEX:
        return "HIPDNN_POINTWISE_GEN_INDEX";
    case HIPDNN_POINTWISE_IDENTITY:
        return "HIPDNN_POINTWISE_IDENTITY";
    case HIPDNN_POINTWISE_LOG:
        return "HIPDNN_POINTWISE_LOG";
    case HIPDNN_POINTWISE_LOGICAL_AND:
        return "HIPDNN_POINTWISE_LOGICAL_AND";
    case HIPDNN_POINTWISE_LOGICAL_NOT:
        return "HIPDNN_POINTWISE_LOGICAL_NOT";
    case HIPDNN_POINTWISE_LOGICAL_OR:
        return "HIPDNN_POINTWISE_LOGICAL_OR";
    case HIPDNN_POINTWISE_MAX:
        return "HIPDNN_POINTWISE_MAX";
    case HIPDNN_POINTWISE_MIN:
        return "HIPDNN_POINTWISE_MIN";
    case HIPDNN_POINTWISE_MUL:
        return "HIPDNN_POINTWISE_MUL";
    case HIPDNN_POINTWISE_NEG:
        return "HIPDNN_POINTWISE_NEG";
    case HIPDNN_POINTWISE_RECIPROCAL:
        return "HIPDNN_POINTWISE_RECIPROCAL";
    case HIPDNN_POINTWISE_RELU_BWD:
        return "HIPDNN_POINTWISE_RELU_BWD";
    case HIPDNN_POINTWISE_RELU_FWD:
        return "HIPDNN_POINTWISE_RELU_FWD";
    case HIPDNN_POINTWISE_RSQRT:
        return "HIPDNN_POINTWISE_RSQRT";
    case HIPDNN_POINTWISE_SIGMOID_BWD:
        return "HIPDNN_POINTWISE_SIGMOID_BWD";
    case HIPDNN_POINTWISE_SIGMOID_FWD:
        return "HIPDNN_POINTWISE_SIGMOID_FWD";
    case HIPDNN_POINTWISE_SIN:
        return "HIPDNN_POINTWISE_SIN";
    case HIPDNN_POINTWISE_SOFTPLUS_BWD:
        return "HIPDNN_POINTWISE_SOFTPLUS_BWD";
    case HIPDNN_POINTWISE_SOFTPLUS_FWD:
        return "HIPDNN_POINTWISE_SOFTPLUS_FWD";
    case HIPDNN_POINTWISE_SQRT:
        return "HIPDNN_POINTWISE_SQRT";
    case HIPDNN_POINTWISE_SUB:
        return "HIPDNN_POINTWISE_SUB";
    case HIPDNN_POINTWISE_SWISH_BWD:
        return "HIPDNN_POINTWISE_SWISH_BWD";
    case HIPDNN_POINTWISE_SWISH_FWD:
        return "HIPDNN_POINTWISE_SWISH_FWD";
    case HIPDNN_POINTWISE_TAN:
        return "HIPDNN_POINTWISE_TAN";
    case HIPDNN_POINTWISE_TANH_BWD:
        return "HIPDNN_POINTWISE_TANH_BWD";
    case HIPDNN_POINTWISE_TANH_FWD:
        return "HIPDNN_POINTWISE_TANH_FWD";
    default:
        return "HIPDNN_POINTWISE_UNKNOWN";
    }
}

inline const char* hipdnnGetReduceTensorOpString(hipdnnReduceTensorOp_t mode)
{
    switch(mode)
    {
    case HIPDNN_REDUCE_TENSOR_ADD:
        return "HIPDNN_REDUCE_TENSOR_ADD";
    case HIPDNN_REDUCE_TENSOR_MUL:
        return "HIPDNN_REDUCE_TENSOR_MUL";
    case HIPDNN_REDUCE_TENSOR_MIN:
        return "HIPDNN_REDUCE_TENSOR_MIN";
    case HIPDNN_REDUCE_TENSOR_MAX:
        return "HIPDNN_REDUCE_TENSOR_MAX";
    case HIPDNN_REDUCE_TENSOR_AMAX:
        return "HIPDNN_REDUCE_TENSOR_AMAX";
    case HIPDNN_REDUCE_TENSOR_AVG:
        return "HIPDNN_REDUCE_TENSOR_AVG";
    case HIPDNN_REDUCE_TENSOR_NORM1:
        return "HIPDNN_REDUCE_TENSOR_NORM1";
    case HIPDNN_REDUCE_TENSOR_NORM2:
        return "HIPDNN_REDUCE_TENSOR_NORM2";
    case HIPDNN_REDUCE_TENSOR_MUL_NO_ZEROS:
        return "HIPDNN_REDUCE_TENSOR_MUL_NO_ZEROS";
    default:
        return "HIPDNN_REDUCE_TENSOR_UNKNOWN";
    }
}

} // namespace hipdnn_backend
